{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 7,
			"minor" : 2,
			"revision" : 1,
			"architecture" : "x86",
			"modernui" : 1
		}
,
		"rect" : [ 782.0, -1001.0, 1074.0, 733.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"boxes" : [ 			{
				"box" : 				{
					"id" : "obj-8",
					"maxclass" : "newobj",
					"numinlets" : 8,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 418.0, 279.0, 192.0, 22.0 ],
					"style" : "",
					"text" : "gen~ octoMix"
				}

			}
, 			{
				"box" : 				{
					"bitcode" : "3sAXCwAAAAAUAAAAfEUAAAcAAABCQ8DeNRQAAAUAAABiDDAkSVm+5u3zfi1EATIFAAAAACEMAABVEQAAC4IgAAIAAAATAAAAB4EjkUHIBEkGEDI5kgGEDCUFCBkeBItigBxFAkKSC0LkEDIUOAgYSwoycohIkBQgQ0aIpQAZMkLkSA6QkSPEUEFRgYzhg+WKBDlGBlEYAAAdAAAAG4ggAJYNhPD/////AyBtQIb/////HwA4ACSA2kAQAJBsMAoBWIBqg2EEwAJUG5Dj/////wcADgAJqDYYSAAsALXBSP7///9/ACSA2mAo/////z8AcABIG5BlABJgAaoNCEMACbAA1Qaj+f////8BaANAAgBJGAAACwAAABOEQJggBMMEgRAmBMUEwTgmCMgwIUgmBMMEIVAmBMqEQJgQGBOGhREmCEEDiSAAAHIAAAAyIsgJIGSFBJMjpIQEkyPjhKGQFBJMjowLhORMEPzDHAGSBwAK5ASABgkBoEJyAOiQBABKJAWAFskAoEbGAOiREQCKZAWAJmkAoEpKAOiSDwDKZAGANrkAoE52AOiTCAAKpWcAgEYpAKBSBgDolDwASmUCgFb5A6BWDgDolTUAimUTgGYjAAQoQs1GtzkCMBgCSEDAAF0CAukSEEKXgAi6HNClgO4eaYooYfIH6WGwQXpQOORyuVwul8vlcrlcLpfL5XK73Y7H4/F4vV6v1/P5fL/f7/f7/X5AIBAIBAKBQCAQCAQCgUAgEAgEAoE6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+koWISakIZzBKBQBFuRjCUQErIMNZuNlKQrRM1mY1KzIDWbjanT6XT0LEbNZmPqdBQtRc3GtNloeo00RZQw+a4ILhSBGttyucQ5nVAoVCqlUrUMNaGVrkXICSlbhpwwR9si6HTULUItR98y1IQ5CheiZrPZaHyPNEWUMPkmMQHgQhFIsJGpXISamc7ELEVNmEunST1HEBSjZgMUc2xqDyMIelCE95vgAwFkIyotCUo4ytF7GIHIg2EEQg9IT+QpAAATrnSYAzywgzYIB3iAB3YohzYgh3CQh3tIB3eIAzhwAztwAzjY0Abl0AbtoAfv0AbwoAdzIAd6MAdy0AbmYAd0oAdzIAd6YAd00AbmgAdwoAdxIAd40AbugAd6EAd2oAdzIAdtMAtxIAd4oPNADBkyUkQEYDDYwoDDcAsDFgMvDHgMvzDgMODCgMkADgMWQy8MuAzjMOAw5MKAzZAOAz6DOgwYDesw4DS8w4DLQA4DJkM4DBgN7DBgNcTDgMtQDgNeAz0MuAzmMGA22MOAw6ALA15DPQy4DfcwYDfsw4DR0A4DTgM8DLgM5zBgMfjCgN/QDwMOwy4MGA3uMOAyoMOA4fAPA4YDSAw4DiEx4Df4w4DlIBIDnsNJDFgN8jDgNuDDgOmAEgNuQz4MWA4jMeA6pMSA5UASA1bDPAyYDOIwYDusxIDvwBIDboM+DFgOJTFgPLTEgOugEgOWg0kMOA8uMWA38MNgyHMHQAAEAgAAAAAAADDkGQUAAAQBAAAAAAAAGPKMAgAAAQAAAAAAAAAMeUwBCIABAAAAAAAAAIY8owAAgCAAAAAAAAAAQx5UAABgAAAAAAAAAIAhzy0AAEAIAAAAAAAAwJAnFwAAKAAAAAAAAABgyJMLAAAYAAAAAAAAADDkyQUAAAwAAAAAAAAAGPLsAgAABgAAAAAAAAAMeXYBAAADAAAAAAAAAIY8vQAEwAEAAAAAAAAAQ55eAALgAAAAAAAAAIAhTy8AAIAAAAAAAAAAwJCnF4AAOAAAAAAAAABgyNMLQAAcAAAAAAAAADDk6QUgAA4AAAAAAAAAGPL8AgAACAAAAAAAAAAMeUYBAIAEAAAAAAAAAIY8owAAgAIAAAAAAAAAQ55wAABgAQAAAAAAAIAhzzkAAMAAAAAAAAAAwJBHHQAAaAAAAAAAAABgyBMOAAAsAAAAAAAAADDkCQcAABYAAAAAAAAAGPK0AxAADgAAAAAAAAAMeeABCIADAAAAAAAAACQ+kCkgsUGgcP0DAEAWCAAAAAQBAAAyHpggGRFMkIwJJkfGBEMKrAFQ0+FENFBJ+ZyyQNKyPT0vk0HiPEjaVEkcnqfHcxc7LX7Zy/J5+u1WiVxmh/NzFzstftnL8nn67VbJGK7P6aBmmI4GMdNieVieV0n+rtPLcxc7LX7Zy/J5+u2mgj7i8Dw9nrvYafHLHW6X9SGX2eH83MVOi1/ucLusj/xdp5fnLnZa/HKH22U66GYM1+d0kDA8T49BRXa5XXbTQcy0WB6W5ymxA+3TO9g+vcPiGLTQyRiuz+kgYpkdzoOYabE8LM/rZE6z6WX53MVOi1/2snyefrt1aofp6LmLnRa/xm94Xp4+o+k6MY9QJuiepqNBZfy4DKen326d5GV7WS6eu9hp8ctels/Tb7dO8/TZHWbPXey0+GUvy+fpt5sauwyEJETIMyFOQw+FA2nZXpaLQeRy+w0Kw+Hs9DhMT7/dIHF4XiaD3m4QWJ+mh7/ysv1rJrvBLoooZE6z6WX53MVOi1/ucLusUDtMR89d7LT4Fa7T0W+5QvKyvSwXz13stPjlDrfLCs3TZ3eYPXex0+KXO9wu00QpY7g+p4OMaTa9LAcx02J5WJ5Xyhiuz+kgadlelotBzLRYHpbnqbIFuGqmt4U0YQuxhSQAC0EXjdphOnruYqfFL3Z6XHbPyxq1w3T03MVOi1/2snyefrspo047TEfPXey0+OUOt8u0WaIBGGIJpXGCJagGmZRgGkFY6qySIROwEtXXnaogjSBiuA1Pu8/0Uc4Yrs/poGn67A6zQdJ3nZ52n0HMtFgelueV06bp4a+0bAcl3fSy3B1mg4xEJ0hatpflYgrtURGRhDjNHpPjLBPy0Eh7wg/Spunhr7RsP81BaTe9LHeH2SAQCITD40DGcpksDo/XIGKZHc6DnGX6/S1fg1BGojMFMoGmY7T8XSaX5aAwmw0Pz+et8bstBsnL9rJcXJaH6W+5CwSalssgEAhkDNfn9NMcJC/by3Lx3MVOi0HmtxxEfo/r7bKbHqan325Q2E0GycvmsrzsHpfnVNqg3kDawN7g3gCn0wgApXQPqDYYqAeip9tlECrtBs3L47ebPE+B6G8QuTwO50E2GFkISrtB7Pe9ZZaX4/Wye5wHicNuMq0UYb7vICnVBlOkmSaDpFQbjFrqB0P5ez5/28tykFlejtfL7nEehELqU6B5GR6Wh+lp9xnEft9BYTcZ1E6TyewyyCwvx+tl9zhdntNrhTCjmNIB1QYD9UD0dLsMQqXdoHl5/HaT5ykQ/Q0il8fhPMgGIwtBaTeonSaT2WWQOOwm00xZwSgvx+tl9zgPQiH1KVCYDrqj02M0iI4ug9DpM7pllpfj9bJ7nAdRbTBQeg5Ch9lmEB1dBrXTZDK73BKH3eTTHES1wQAAALEYAABWAAAAMwiAHMThHGYUAT2IQziEw4xCgAd5eAdzmHEM5gAP7RAO9IAOMwxCHsLBHc6hHGYwBT2IQziEgxvMAz3IQz2MAz3MeIx0cAd7CAd5SIdwcAd6cAN2eIdwIIcZzBEO7JAO4TAPbjAP4/AO8FAOMxDEHd4hHNghHcJhHmYwiTu8gzvQQzm0Azy8gzyEAzvM8BR2YAd7aAc3aIdyaAc3gIdwkIdwYAd2KAd2+AV2eId3gIdfCIdxGIdymId5mIEs7vAO7uAO9cAO7DADYsihHOShHMyhHOShHNxhHMohHMSBHcphBtaQQznIQzmYQznIQzm4wziUQziIAzuUwy+8gzz8gjvUAzuwwwzHaYdwWIdycIN0aAd4YId0GId0oIcZzlMP7gAP8lAO5JAO40AP4SAO7FAOMyAoHdzBHsJBHtIhHNyBHtzgHOThHeoBHmYYUTiwQzqcgzsAAACpGAAABgAAAAsKciiHd4AHelhwmEM9uMM4sEM50AMAAGEgAAAJAAAAEwQBhgMBAAAFAAAA5hgwDNJzAAvRTBH2B4sjKAAAAAAAAAAAYSAAAAoAAAATBMEFth0xKIAQBIM7uIUAw4EAAAMAAAAHUBDNFGHmGDAM0gMAAAAAYSAAAAkAAAATBAGGAwEAAAUAAADmGDAM0nMAC9FMEfYHiyMoAAAAAAAAAABhIAAADgAAABMEQSwQAAAAAgAAAFQsQHhUAwAAIwYFEIJgYAqzEFwg3AzCgQAAAAACAAAAB1AQzRRhAAAAAAAAYSAAAPAAAAATBEEsEAAAAGwAAACUK4RyDCjFgKIMKIeCDCiCwhgBINtQxxiQwRjkAU7kAU4MdXxgQAZ5gBN5gBNDHWVgBmWQBziRBzgx1JEGapAGeYATeYATQx1rwAZskAc4kQc4MdRRBmbQBnmAE3mAE0MdbeAGcJAHOJEHODHUsXFykAc4kQc4MdRRBmYwB3mAE3mAE0MdcSAHdJAHOJEHODHUsQZsUAd5gBN5gBNDHWVgBnaQBziRBzgx1DEHdHAHeYATeYATQx2dhwd5gBN5gBNDHW8AB3GQBziRBzgx1FEGZrAGeYATeYATQx2J8gZ5gBN5gBNDHZXlBnmAE3mAE0MdG6cGeYATeYATQx0bhwZ5gBN5gBNDHZV1BnmAE3mAE0MdZ4AGZpAHOJEHODHUEQZiIAZ5gBN5gBOkGyMAQRAEQRAEQf4fxghAEARBEARBEAWJMQKdNeecNeecdf9hjAAEQRAEQRAERZAYIwBBEARBEARRHSTGCEAQBEEQBEFUBokxAhAEQRAEQVAfQ2KMAARBEARBEARBkBgjAEEQBEEQhPc2JMYIQBAEQRAE4b0MiTECEARBEARB/K5DgpgjAADXBvOlwDZ2dXgDMzgDCqhjxAABQhAMZiEYiugMdnWIAzRQAwqWY8TAAEIQDFQhKNCACOrYwaEO1sANRgwQIATBYBaEI0gDiwzqGDFAgBAEg1kIEAHL6KCOEQMECEEwmIUgGS41IIQ6RgwQIATBYBYCheC+XR3w4A3mgALoGDFYgBAEg1cIGDYwrAy7aKGOHRz4QA7uYMQAAUIQDGZBcII26KihjhEDBAhBMJiF4BHEYAzIoY4RAwQIQTCYhQAawCAM6KGOEQMECEEwmIUgIr43IIg6RgwQIATBYBYCqSADNCAEOkYMFiAEweAVggkODG7TwIAk6tjBYRTy4A9GDBAgBMFgFoQqiAMyIIo6RgwQIATBYBYCS0gDNaCKOkYMECAEwWAWgms4AzQgizpGDBAgBMFgFgKMMIM5oIs6RgwQIATBYBaCrFgDN6AHOkYMFiAEweAVAo0ODDA4AzMoA8qoYwcHVQCFUxgxQIAQBINZELigDtaANuoYMUCAEASDWQg6AQ7igDjqGDFAgBAEg1kIvMEN3oA66hgxQIAQBINZCD6iDe6APOoYMUCAEASDWQjAoJADOyALOkYMFiAEweAVgjDAA8MMyoAM3GBXh1cwBVegADdGDAogBMHgDoIxwHAgAAAABgAAAPYYkCDNREQFIBAHQCANMpljwDBIDwAAAAAAAABhIAAADwAAABMEQSwQAAAAAgAAAJQbASgRAAAAOzgMQkBBbmQQDgQABQAAAOYYMAzScwAL0UwR9geLIygAAAAAAAAAAGEgAAAMAAAAEwRBLBAAAAABAAAAlCsIABmEAwEFAAAA5hgwDNJzAAvRTBH2B4sjKAAAAAAAAAAAYSAAAAwAAAATBEEsEAAAAAEAAACUKwgAGYQDAQUAAADmGDAM0nMAC9FMEfYHiyMoAAAAAAAAAABhIAAAFAAAABMEQSwQAAAAAgAAAJQriBKoAQAAww3EQAbTDYMQZBAOBAAAAAkAAAAHsBDNFGF/sDiCYo4BwyA9RhlgRMRUAYs9BhzCATQNsQAAAAAAAAAAYSAAABQAAAATBEEsEAAAAAIAAACUK4gSqAEAAMMNxEAG0w2DEGQQDgQAAAAJAAAAB7AQzRRhf7A4gmKOAcMgPUYZYETEVAGLPQYcwgE0DbEAAAAAAAAAAGEgAAAKAAAAEwSBBYF8MggHAgAABQAAAAewEM0UYX+wOIJijgFFBSwUAQAAAAAAAGEgAAAKAAAAEwQBhgMBAAAGAAAA5hjASADzLEhjfBEBHcBCNFOE/cHiCAoAAAAAAGEgAAAiAAAAEwRBLBAAAAAPAAAAlBsBKMWAcgwoygDSjRGAIAiCIAiCIAgSYwQgCIIgCIIgqoMEvccSQBAEQRAE4b0NCRAEQRAEQRAUQQIAOzgghzFsQATEAOzgkCDGBfkdNiACYgB2cFiUY9iACIwBwHAgBQAAAOYYMAzScwAL0UwR9geLIygAAAAAAAAAAGEgAAAaAAAAEwRBLBAAAAAFAAAABBgBoNwIQIEUSSFQsQATy4g9AgA7OCBGMWxABMcArCCRHMVxgW1HDBIABMGgHUwhUAqDwHAgAAAHAAAA5hgwDNJjlwGKJBCVQTz5Th/AQjRThP3B4ggKAAAAAABhIAAAcAEAABMEQSwQAAAAcgAAAJQbASiBGYAiKIPy/yv/jxIpwoAyDCjEgGIMKMmAsgwozYDiDCiMAg0o0YCyKIoyDSjUgGINKNeAYijZgKINKIVCKNuAwg0o3YDyDSjgANKPRfzf/z//H/z/Mxbx/8H/P//3/8dYBBAIxRwETNDETMjEHIRMxIRMyMRYxP8H/3/83/8fYxFAIRxjEUAgEHMQMCETMiETpBsjiEE8fW98f3nxH8YIdLSEZ3YH3Vv+hzGCVn9T0rdd/z3/YYwAFeHYzXceHul/GCMA+fo1z/WnefIf6D0DMJYAgiAIgiAIgvg/gCAIgiAIgiD+D2MJJ7jXZj7LtVn+AzvSb/ruPy/H/zCWYO80zdc1Se/lP8QgiMd97vMi/A9jCWXew62Ys26I/gMIgiAIgiAIwv8wh8AXrjGWkPfqW6OmHqLmP5C1yf59yvak/A9jCfEKwqaql/1v/oN9iuocpjUazv9AujECHF1RUm3/MBVBYowAR1eUVNs/TE2QGCMocTvGZ/bOefgfxghAEARBEAThPRSJMQIQBEEQBEEQ5P9hBmCMAARBEARBEATxfxgjAEEQBEEQBEH+X8YIwv7/cVaNw94EGdrPQcCGa7iGa8wAADs4mAIp9MGwARGYwgCcKehsOCJIiG+6QRGC4YiAEb7phkYIdnBgBVUQhWEDIhAGwARIPhY08BkxMIAQBIuvF3Ai2MEBFlyhFIYNiEAYABMc+Vhw0GcHh1mIhVMYNiACYQAMS+izg0MtzAIqDBsQgTAAti302cHhFmohFYYNiEAYgB0ccMEWUmGOwQycW5hjCJ5bsMAM5GMBGsBnxKAAQBAM4OEmgkGGYA3iYAxB6IUxhKEXLsnvsAERFANgwicfCzD67OBADuJAC8MGRCAMwA4O5TAOtGAMHMjHgjmAz4hBAYAgGMCDWARjCME5zDGUQYAOcwzBgg5zDEFzDnMMgXcOcwxqUKzDHEPQBuowyBBIpGBEAB8rhPgMMggBKlygpwpWQXdwsAd6IIcL+DtsQATDANyU32EDIogGYAwhsgcL7kA+FsABfXZw4Ad9SIdhAyIQBmAHh37Yh3QwMjgF+ViwCvAZMSgAEAQDeNCLYJAhcAVcGEMQQGIMYQAJW4T4XJCjCv5Bd3A4iZKQh2EDIhAGwAxTgM8FOapAJHQHh5VIiXoYNiACYQDuye+wARE0A2CKKsjHglGgzw4OL9ES+DBsQATCAOzgABMugQ9UCroxx6ALwUvMMegBOcCECYF8LAgH+IwYFAAIggE8wEYwyBCQgzqMIQg1cUl+hw2IgBgAE25BPhYo9NnBgSd0YiSGDYhAGIAdHHpiJ0ZijmEdGp6YYwgcnrDgHORjQTvAZ8SgAEAQDOCBN4IxhCAsBhkEhx8GGQIy8Ic5BnEYxmKOISgHsRhkCCJ+MCKAjxVCfAYZhAAkLtBTBSehOzi4BVvMxAX8HTYggmEAbsrvsAERPAMwhvC4hQXvIB8LxIA+OzjQhVzgxLABEQgDYGRQEvKxoB7gM2JgACEIFl8vgEiwgwNe2MVODBsQgTAAhgjxuSBHFdCF7uDAF3rhE8MGRCAMgBn7AJ8LclTBXegODqDhF2ExbEAEwgAYHMCEfCwICfiMGBhACILF1wssEuzgQBqiQRbDBkQgDIAJIiEfC+qAPjs4nEZpmMWwAREIA7CDA2qYhlmYGryEfCywCfiMGBQACIIBPJRIMMgQ5MRPjCEIqzGGMKzGHfkdNiCCYgBMaAn5WAAK9NnBQTZg4y2GDYhAGAAThbCQjwUzAZ8RAwMIQbD4esFHgh0cbIM25GLYgAiEAZhjkAmhNuYYAqU25hgChjbmGIKLNuYYbsLAjTmGQCduY5AhiOLCiAA+VgjxGWQQgrq4QE8V9IXeePB32IAIhAHAcCAIAAAA5hgwDNJjjwGMBDDPgjTGFxHQASxEM0XYHyyOoAAAAAAAAAAAYSAAAKMAAAATBEEsEAAAAFoAAACUK4ERALINdVQWlAcwkQcwMdTxgUGXBzCRBzAx1BEIQB7ARB7AxFDHQAR5ABN5ABNDHYUh5AFM5AFMDHUcyJAHMJEHMDHUMRBEHsBEHsDEUEdhGHkAE3kAE0MdC3PkAUzkAUwMdQwEkgcwkQcwMdTROEkewEQewMRQxwMpeQATeQATQx2RtOQBTOQBTAx1TBSTBzCRBzAx1LEwTR7ARB7AxFBHJD15ABN5ABNDHQsT5QFM5AFMDHVcmJQHMJEHMDHUsTBTHsBEHsDEUEemUXkAE3kAE0MdA1HlAUzkAUwMdVyYlQcwkQcwMdSxcVcewEQewMRQR+dheQATeQATQx2RlOUBTOQBTAx1TJSWBzCRBzAx1LEwWx7ARB7AxFBHYXB5ABN5ABNDHQPh5QFM5AFMDHVE0pcHMJEHMDHUsTBgkAcwkQcwMdQRBmIQBnkAE3kAE0MdieLkAUzkAUwMdSRKkQcwkQcwAQBXBvOlwDZWeTiDMjADCshjxOAAQhAMxiEYyGAMRgwOIATBYByCQQzCYMTgAEIQDMYhGMCgGDE4gBAEg3EIhs8bMTiAEASDcQiGrhgxOIAQBINxCAZuGzE4gBAEg3EIBi0bMTiAEASDcQgGzBgxOIAQBINxCIbLDEYMDiAEwWAcgsEygxGDAwhBMBiHYKioEYMDCEEwGIdgmKQRgwMIQTAYh2CIjBGDAwhBMBiHYICeEYMDCEEwGIdgcJoRgwMIQTAYh2BgihGDAwhBMBiHYFjKYMTgAEIQDMYhGJRixOAAQhAMxiEYkjIYMTiAEASDcQgGpBgxOIAQBINxCIajwHAgBAAAAAewEM0UYX+wOIJijgEBAwAAAAAAYSAAALEIAAATBEQsEAAAAG8AAACUGwEogfL/K/+P8n8o//+AIiiEgimgwimUMiiFYiiHIiqQUimfAhcsK5aiKUDBsnIpmwIeLCvowLIiKcjBspIpnTIpnoIfLCuhggwsK+DAsoIPLCtowbICHCwr2MGyAh8sK8WAQgwoxoByDCjIgJIMKMqA0gwo0IAyDSjWgJINKNyA8g0oqrIqSMKygiUsK7wCJywruIImLCvAwrKCFywreMKyAi0sK8jCskIr4MKyAivYwrICLywrSMGygi4sK0DDsoIvLCvAgMIqUMOygipIw7ICNiwr6MGygjUsK3DDsoI2LCukAjwsK3jDsgI9LCvwwLKCPCwr4MOygj0sK/DDsoI+LCtAxLICHSwr+MOyAkUsK0jEsgJGLCtYxLKCFSwrYMGyAkcsK2jEsgJMLCt4xLLCKNDEsoIoyMSyAiQsK+DEsoJNLCvwxLKCTiwrQMWygk8sK1DBsgIlLCtgwrICDSwj3RgBCIIgCIIgCPL/MEYAgiAIgiAIgvy/jACMEcw5a845a845/i9jBHPOmnPOmnOO/8MYAeu7/jnnM1jX/zBGMMYwmZokzfPxPYwRgCAIgiAIgiAIIgAAAACUEsyxmYJKnAQFzLGZAkuQBAXMsZmCS4AEBcyxmQJMnAQFzLGZgkyMBAXMsZkCTZAEBcyxmYJNlAQFzEE3wRybKeCETVDAHJsp6MRMUMAcmynwxEtQwBybKfiETVDAHJspgIVMUMAcmymIxUxQwBybKZAFTVDAHDs4pEVZ6AMFurGDw1qcxT5QoBsWDPQZMTCAEASLrxfsI7AgkM8ODnDBFv9AgW7s4CAXbgESFOiGBYN8RgwMIATB4uuF/QgsOORjdBDEx+ogiY8JgnxMEORjQkAfC/AAPsMRAR4Q33RDHgjBiIEBhCBYfL1AIoElCH1M8AP4WCDEx4JKPjs4kAZoxAQFumFaQJ8RAwMIQbD4euFFAgs0+lhQCvDZwUE1TMMmKNCNHRxYAzVuggLdsGCQz4iBAYQgWHy9MCOBtUJAHwtcAT72CkJ8LBDoY6oQxMdkgaCPWVd8dnC4jdkICwp0w4I3oM+IgQGEIFh8vSAmgQWBfCw4A/mYLgTxsV0Y4mOCIB8TBPmYENDHAl+Az3BE4AvEN93wC0IwYmAAIQgWXy+oSWAJQh8TyAE+FgjxseCRj0llQJ8RAwMIQbD4emFOAgsk+liQDvAxJInPDg7vsR54QYFuWHAK9BkxMIAQBIuvF/QksCCQjwV/IB+ThyA+Ng9DfEwQ5GOCIB8TAvpYYA/wGY4I7IH4phvuQQhGDAwgBMHi6wVRCSxB6GMCP8DHAiE+FjzyMakP6DNiYAAhCBZfL6xKYIFEHwtCAj6GJPHZweFERuQ1KNANC36BPiMGBhCCYPH1gqwEFgTyseAW5GMqEcTHVmKIjwmCfEwQ5GNCQB8LXAI+wxGBSxDfdMNLCMGIgQGEIFh8vaArgSUIfUygCfhYIMTHgkc+JtUCfUYMDCAEweLrhXEJLJDoY0FOwMeQJD47OPzIjpgHBbphwT3QZ8TAAEIQLL5eUJfAgkA+FryDfEwsgvjYWAzxMUGQjwmCfEwI6GOBWcBnOCIwC+KbbjgLIRgxMIAQBIuvF+QlsAShjwlsAR8LhPhY8MjHpHagz4iBAYQgWHy9sC+BBRJ9LIgL+BiSxGcHhzuZk/6gQDcseAn6jBgYQAiCxdcLIhNYEMjHgpOQj+lFEB/biyE+JgjyMUGQjwkBfSzwC/gMRwR+QXzTDX8hBCMGBhCCYPH1gsoEliD0MYE04GOBEB8LHvmYVBL0GTEwgBAEi68XZiawQKKPBakBH0OS+Ozg8CqrQiMU6IYFZ0GfEQMDCEGw+HpBZwILAvlY8BPyMdkI4mOzMcTHhIA+NgzysWGQjwkBfSy4DfgMRwS3QXzTDbghBCMGBhCCYPH1wtgEhgTxMaE34GOBEh8LIPnY5BP0GTEwgBAEi68X2CawYKKPBeIBnx0czmVc1oQC3bDgL+gzYmAAIQgWXy/ITWBBIB8L7kI+ph5BfGw9hviYENDHhkE+NgzyMSGgjwXvAZ/hiOA9iG+6AT6EYMTAAEIQLL5e2JvAkCA+JtQHfCxQ4mMBJB+b7II+IwYGEIJg8fUC6QQWTPSxQD/gM9zgL/tiBrMMwRDsIAEy/DIq+7KDRMj0S7vwyw4SIuMv7oIvO0iMzL+Uir/s4EAyIPMuVOgGFbpBhW5QoRtU5MYsgTBQkQdCsKeBMFChB0bwpoEwUKEHSvC6gTBQoQdOsLqBMFChB1IQpoEwUJEHNhaUbiAczODXhr6QjxkFfCzwC/lYMMDnaiaXFdwKXMDUYQMiIAbAiNeQjwUMfOw2AvkYVBryMSGAz/VMLivwFbiAqcMGREAMQFk6oztIhE3PrExgho7IxwIdgc+wATEEA7B0Qo5UFOjGmU0uKzAXuACvFORGgUEQFZSN7iDBNmhjMwEFumFBAp97m1xW4C5wAVMp0A0L2kQ+ZgTwqTVoG91Bwm7k5meCYQMiGAbg7iaXFdQLXIBXCnKj4iCICuhGd5Dom7wxm4AC3bi/yWUF/AIXMHXYgAiIATBnT+RDkm5YIMDnSieXFYQMXMBUCnTDgvqQz6lOLiuYG7iAqRToxrlOLitIGbiAqRTohgUFfCzwD/lYsMDnaieXFbwMXMDUYQMiIAbAiPWQjwUMfCw+Avnc7uSyApqBC5hKgW5YEB/yMSOAz4VPLivIGbiAqcMGREAMwA4S5AM+q0MKVvSKfCzoFfgMGxBDMABLJ9AKLlCgG5c+uawAbOACvFKQGzUOQVSAPrqDxPusj+0EFOiGBQl8Tn5yWQHawAVMpUA3LIAX+ZgRwKfcIX50B4n8qZ/fCYYNiGAYgNOfXFbwNnABXinIjaKHICrAH91BAoT4x3wCCnTjRCiXFdgNXMDUYQMiIAbAHH+RjwWiAB+adMOEAD6XQrmsgG/gAqZSoBsW5Il8zoVyWQH9wAVMpUA3ToZyWQHpwAVMpUA3LCjgY4GoyMeCBT6XQ7msQHXgAqYOGxABMQBG3Ih8LGDgYz0SyOd+KJcVvA5cwFQKdMOCHpGPGQF8roxyWQHtwAVMHTYgAmIADo1yWYHtwAV4pSA3KjAj3UGijdIohgJTzEY+FpgNfIYNiCEYgKUTwiYsKNCNk6NcVvA7cAFeKciNWoKoII50Bwk8oiMeCijQDQsS+Nwe5bKC84ELmEqBbliQN/IxI4BPWXqkO0iIkh+VUTBsQATDANwo5bIC94EL8EpBbhQXRAWhpDtIpFIpsVFAgW7cKuWygvqBC5g6bEAExACYczryuVfKZQX4AxcwlQLdsOBf5HO0lMsK7gguYCoFunG4lMsKQAguYCoFumFBAR8LUEY+FizwuV/KZQUmBBcwddiACIgBMKJU5GMBAx9blUA+V065rGCF4AKmUqAbFqyKfMwI4HPrlMsKYAguYOqwAREQA7CDhDupkziJghXnIx8Lzgc+wwbEEAzA0gm6Ix4U6MbNUy4ruCG4AK8U5EaxQhAVyJPuIJFP9dROAQW6YUECn+OnXFbwQ3ABUynQDQv0Rz5mBPCpW9An3UFipP7JnoJhAyIYBuBIKpcV4BNcgFcKcqN6IYgKQkp3kFApk+qngALdOJbKZQVuBBcwddiACIgBMAeF5GOigBLwIVrQDaJ0wwYCPhYM8LFggM/ZVC4ruCO4gKkU6IYFpiOf26lcVtBPcAFTKdCN+6lcVvBHcAFTKdANCwr4WPA68rFggc+ZVS4rKCW4gKnDBkRADIAR9CIfCxj4mL4E8jm2ymUFqgQXMJUC3bBAX+RjRgCfk6tcVvBKcAFThw2IgBiAUgm20h0k7EqubCow443kY8EbwWfYgBiCAVg6gY3UhALduL3KZQVuBRfglYLcKJoIooK70h0kQquvwiqgQDcsSOBzpJXLCsAJLmAqBbphQSjJx4wAPjtIqJZp8VVKDBsQgTAAFBa5cayVywpCCy7AKwW5UUUQFaiW7iAhW65FWgEFunG0lcsK3gkuYOqwAREQA2BOLMnncCuXFcgTXMBUCnTDAhSSz/VWLivoK7iAqRToxoVXLivQJ7iAqRTohgUFfCyIIflYsMDn0CuXFYAUXMDUYQMiIAbACJ+RjwUMfIxsAvmce+WygpKCC5hKgW5YQDbyMSOAz9FXLitQKbiAqcMGREAMQLFBfOkOEvhFX7YVmBFP8rEgnuAzbEAMwQAsnWBO7EKBblx/5bKC94IL8EpBbpQdBFEBf+kOEiP2X+EVUKAbFiTwORPLZQU7BRcwlQLdsGCk5GNGAJ8KhRLTHSRaLMXUKxg2IIJhAM7FclmBfsEFeKUgN+oUgqiAxXQHCRqDsfgKKNCNs7FcVqBWcAFThw2IgBgAc2ZKPqdjuaygreACplKgG+djuawAruACplKgGxYU8LHAleRzZJbLCuoKLmAqBbphAS3Jx4wAPqdmuaxAr+ACpg4bEAExANdmuayAr+ACplKgGxbIjnwsYR35mBXAx2QnkI8FBHzOznJZAWnBBUwdNiACYgDKHeBMd5DQMzuzscCMuZKPBXMFn2EDYggGYOkEtnIbCnTj/iyXFbAWXIBXCnKj8CGICvZMd5AotVALs4AC3bAggc+hWi4roC24gKkU6IYFpSUfMwL47CDhaqqWZqIwbEAEwgDcq+WyAt2CC/BKQW4USgRRQavpDhK1FmtwFlCgG3druawgvOACpg4bEAExANbQlnxu13JZgZ3BBUylQDfu13JZAXrBBUylQDcsKOBjwUvJ58otlxW0F1zAVAp0w4Kako8ZAXxu3XJZgXzBBUwdNiACYgDO3XJZAX3BBUylQDcs2B/5WFI/8jErgI/tTyAfCwj43L3lsgL+gguYOmxABMQAEKzkRgXypjtI8Bu+tVtgR33Jx4L6gs+wATEEA7B0gnnBDwW6cSGXywpKDC5gKgW6YYF/yccCAz53crmsoN/gArxSkBsVBVHByOkOEi2Xcv4WUKAblgTwKQvldAeJmGs5dQuGDYhgGAASodyoLIgKWE53kKi5mHO3gALduJvLZQU6BhcwddiACIgBsIXG5GOkYSLwIdvQDaoJ3aBNN6gWdMOKk4CPBacAHwsQ+FhwwMeCAz4WHPCx4IDPnV0uKwA5uICpwwZEQAyA1chsxMcCmYiPBbIQHwum+FggxccCKT4WSPGxQIrPyV0uK1A5uICpwwZEQAwA4YtuEJ7ohtnJvcDHgjiTjxEBfIwI4GPkMTfwsWAs4GPBOMTHAjKIjwVjAB8LxgA+FhzxsYAM4mMBGcTnSC+XFewcXMDUYQMiIAbA/gY+4mPBW8THgneAjwVwAB8LovhY4AbwscAN4GOBHMTHAjmIz8FeLiuQNbiAqcMGREAMgJXMC8HHgg8+FD66YUHswMcCVIGPiUEAH4MR14iPBS0BHwtYIT4W2Jp8LEjgY4EowMcCUICPBUh8LCCF+FhACvG58ctlBXkHFzB12IAIiAGw3eiR+FigE/GxIBfgY8G4yccCCz4WTPGx4BXgY8ErwMcCWYiPBbAQn4O/XFZQenABU4cNiIAYACOXN4KPBX4AH/vOBj4WhAJ8zFOL+FiQDvCxYN7kY4EBHwt+AT4WGPGx4BfgY0E4xMcCcIjPgWCQywpoDy5g6rABERADYJ1dwMeCeoiPBf8mHwsk+FgQxceCdYCPBeoAHwvcIT4WtEN8jgWDXFbwe3ABU4cNiIAYgKUT6g2khg2IQB0GgHhBN5ZOqDeRGjYgAmEAiBV0Y+mEeiOpYQMiEAaAREE3lk6oN5MaNiACYQAoDnRj6YR6Q6lhAyIQBoDMQDeWTqg3lRo2IAJhAAjTjaUT6o2lhg2IQBgAcnRj6YR6c6lhAyIQBoBOSjfuB4NcVgB2cAFThw2IgBgAGinduDEMclnB2MEFTB02IAJiAIh/cqMCMQxg2IDwn2AA6Jx0Y9iAwKdgAEiWdGPYgBinYADolHRj2IBwpWAA6Ix0Y9iAwKNgACiGdGPYgBCjYADIhHRj2IBooWAAKHx0Y9iAkJ9gAMh1dGPYgPidYABodHRj2IBQnWAAaGx0Y9iAoJtgAEhldGPYgNiZYADoX3Rj2IAwmWAAyFd0Y9iAeJdgAGhVdGPYgOCVYAAIVHRj2IA4lWAA6Ed0Y9iAgJNgAIhFdGPYgJiRYAAoRHRj2IBYkWAAKDx0Y9iAiI9gAMg1dGPYgKiNYABoNHRj2IBojWAAiCx0Y9iA2ItgAM4Pg1xWcIMBXJBXCt7jRDHIZQWhBxfkddiACIgBuFIMcllBDwZwQV4peI9LxSCXFaxhABfkddiACIgBOFYMclnBGAZwQV4peI+DxSCXFdhhABfkddiACIgBoDvRjWEDgk6CASCR0I1hAyJPggG4WgxyWcEaBnBBXil4j8vFIJcViGIAF+R12IAIiAE4XgxyWUEcBnBBXil4jwPHIJcVgGIAF+R12IAIiAG4cQxyWcEdBnBBXil4jzvHIJcVqGIAF+R12IAIiAE4dQxyWUEfBnBBXil4j3PHIJcVpGIAF+R12IAIiAEw8WLHAAZjCHHgjsEYghy4YzDcMI/BAAazDIMQYDgQAADbAwAANniwSFSjAMMQ2ThuhAeLRDUKMAyRjefWb7BIVKMAwxDZeG3+BotENQowDJGN29Z4sEhUowDDENk4b5QHi0Q1CjAMkY33VomwSFSjAMMQ3XRviweLRDUKMAyRjevGeLBIVKMAwxDZ+G7UCItENQowDNFt3+aNsEhUowDDEN02bt8Ii0Q1CjAM0W3nBo6wSFSjAMMQ3bZu8QiLRDUKMAzRbe92i7BIVKMAwxDd9W7ACItENQowDNFd8xaMsEhUowDDEN11b/4Ii0Q1CjAM0X3TVnmwSFSjAMMQ2Tlt3wWLRDUKMAxRvdMmXrBIVKMAwxDVe23jBYtENQowDFG920ZesEhUowDDENX7beYFi0Q1CjAMUb3jdl6wSFSjAMMQ1Xtu6AWLRDUKMAxRvevWXrBIVKMAwxDV+34AC9FMEfYHiyMo5l6wSFSjAMMQ1Ttv7wWLRDUKMAxRvffGebBIVKMAwxDZuW2dB4tENQowDJGd3+Z5sEhUowDDENk5bqQHi0Q1CjAMkZ3nZnmwSFSjAMMQ2XltpgeLRDUKMAyRne+GerBIVKMAwxDZOW+pB4tENQowDJGd9zaPsEhUowDDEN12b6UHi0Q1CjAMkZ3rJo2wSFSjAMMQ3XZt0wiLRDUKMAzRbdv2mLBIVKMAwxDdN26QCYtENQowDNF95yZLcEgCURnEY5sJi0Q1CjAM0X3v9o+wSFSjAMMQ3Xdt8giLRDUKMAzRbfPmmLBIVKMAwxDd922uCYtENQowDNGN06Z6sEhUowDDENk6bfMFi0Q1CjAMUc3TRl+wSFSjAMMQ1Xxt9QWLRDUKMAxRzduWX7BIVKMAwxDV/G36BYtENQowDFHN47ZfsEhUowDDENV8boEGi0Q1CjAMUc3rJmiwSFSjAMMQ1fxugwaLRDUKMAxRzfOmaLBIVKMAwxDVfG+sB4tENQowDJGt19Z6sEhUowDDENm6ba4Hi0Q1CjAMka3fJnuwSFSjAMMQ2TpusweLRDUKMAyRredGe7BIVKMAwxDZum64B4tENQowDJGt75Z7sEhUowDDENk6b7oHi0Q1CjAMka331pqwSFSjAMMQ3XdvjwGF4FDNZLEJi0Q1CjAM0Y3bBpiwSFSjAMMQ3bdtpASKRDUKMAwRz1spgSJRjQIMQ8T31pywSFSjAMMQ3bhumgmLRDUKMAzRfev2mrBIVKMAwxDdeG2cCYtENQowDNF98yabsEhUowDDEN34bbMJi0Q1CjAM0Y3jxpywSFSjAMMQ3XhuuweLRDUKMAyRvdO2aLBIVKMAwxDVPW2MBotENQowDFHd1yZpsEhUowDDENW9bZMGi0Q1CjAMUd3fRmmwSFSjAMMQ1T1umgaLRDUKMAxR3ee2abBIVKMAwxDVvW6cBotENQowDFHd70ZqsEhUowDDENU9b6UGi0Q1CjAMUd33xnuwSFSjAMMQ2XttvQeLRDUKMAyRvdtGfLBIVKMAwxDZ+23FB4tENQowDJG942Z8sEhUowDDENl7bqsEikQ1CjAMUU8bK4EiUY0CDEPU19ZKoEhUowDDEPW20RIoEtUowDBE/W21BIpENQowDFGPmy2BIlGNAgxD1OfWS6BIVKMAwxD1uvkSKBLVKMAwRP1uvwSKRDUKMAxRz1sxgSJRjQIMQ9T3lp2wSFSjAMMQ3bluzQeLRDUKMAyRvevmfLBIVKMAwxDZ+27PB4tENQowDJG982Z9sEhUowDDENl7b9cJi0Q1CjAM0Z3jhp2wSFSjAMMQ3Xlu1weLRDUKMAyRzdOGfbBIVKMAwxDZfG3dB4tENQowDJHN2+Z9sEhUowDDENn8bd8Hi0Q1CjAMkc3jVn6wSFSjAMMQ2Xxu5geLRDUKMAyRzet2frBIVKMAwxDZ/G7pB4tENQowDJHN86Z+sEhUowDDENl8b9sJi0Q1CjAM0Z3zJp2wSFSjAMMQ3Tlt0wmLRDUKMAzRnddGnbBIVKMAwxDduW3VCYtENQowDNGd3/adsEhUowDDEN16beAJi0Q1CjAM0a3bNp6wSFSjAMMQ3fptzgmLRDUKMAzRje8GnbBIVKMAwxDdOG/RCYtENQowDNGN94aesEhUowDDEN36bukJi0Q1CjAM0a3zpp6wSFSjAMMQ3Xpv5AmLRDUKMAzRreNWnrBIVKMAwxDdem7nCYtENQowDNGt6+adsEhUowDDEN06bdoJi0Q1CjAM0Z3vxp2wSFSjAMMQ3Xlv6wmLRDUKMAzRvdO2frBIVKMAwxDZPW3tB4tENQowDJHd1+Z+sEhUowDDENm9be8Hi0Q1CjAMkd3fNn+wSFSjAMMQ2T1u9AeLRDUKMAyR3edWf7BIVKMAwxDZvW75B4tENQowDJHd76Z/sEhUowDDENk9b/sHi0Q1CjAMkd33xp6wSFSjAMMQ3Xtt7gmLRDUKMAzRvdv2nrBIVKMAwxDd+23wCYtENQowDNG94xafsEhUowDDEN17bvIJi0Q1CjAM0b3r5hgwDNJj9QmLRDUKMAzRvfNmn7BIVKMAwxDde2/zCYtENQowDNG971ZPkEgCURnEs9/mW5BIAlEZxLPj9l+QSAJRGcSz53ZskEgCURnEs+uWeJBIAlEZxLPvtnyQSAJRGcSz89aIkEgCURnEs/eGn7BIVKMAwxDdfG35CYtENQowDNHN26afsEhUowDDEN38bfcJi0Q1CjAM0c3T1p+wSFSjAMMQ3Xxu/gmLRDUKMAzRzevGn7BIVKMAwxDdPH4DTERMVNT8weIIinUmJJJAVAbx8LR9JiSSQFQG8fC1hSYkkkBUBvHwto0mJJJAVAbx8LeVJiSSQFQG8fC4nSYkkkBUBvHwuaUmJJJAVAbx8LqtJiSSQFQG8fC7TRIQ/hMRBhlgIM1DTZIZEywS1SjAMEQ1TdsxwSJRjQIMQ1TTtTUTLBLVKMAwRDVtmzPBIlGNAgxDVNO3PRMsEtUowDBENY3bNMEiUY0CDENU07lREywS1SjAMEQ1rVs1wSJRjQIMQ1TTu2ETLBLVKMAwRDXNWzbBIlGNAgxDVNO9RQYcDjU91CRZMIHhN4RR00ZYYPgNYdS1NRcYfkMYtW2OBobfEEZ9W7mB4TeEUeN2emD4DWHUuaEfGH5DGLVuqAiG3xBGvZs2wSJRjQIMQ1TXtHETLBLVKMAwRHVdWzfBIlGNAgxDVNe2eRMsEtUowDBEdX3bOMEiUY0CDENU17iREywS1SjAMER1nVs5wSJRjQIMQ1TXuqUTLBLVKMAwRHW9mzrBIlGNAgxDVNe8rRMsEtUowDBEdd0bJYHhPxGh94aLYPgNYdi25SIYfkMY9m26CIbfEIaN2y6C4TeEYefGi2D4DWHYuvUiGH5DGPZuvgiG3xCGzds9wSJRjQIMQ1Tbt+ETLBLVKMAwRLWN2zvBIlGNAgxDVNu0wRMsEtUowDBEtV2fwCI4A/EHiyMotgEWLBLVKMAwRLWtW2DBIlGNAgxDVNu7CRYsEtUowDBEtc1bPMEiUY0CDENU27ZVEhj+ExE7bZYEhv9ExF7bJYHhPxGx26ZqsEhUowDDENm0basGi0Q1CjAMkU3f1mqwSFSjAMMQ2TRuiAWLRDUKMAxRbfeWT7BIVKMAwxDVdm6pBotENQowDJFN11ZrsEhUowDDENk0b7YGi0Q1CjAMkU335mqwSFSjAMMQ2XRurwaLRDUKMAyRTetmarBIVKMAwxDZNG3JCIbfEMZdmzKC4TeEcd+2jGD4DWHcuDEjGH5DGHduiQWLRDUKMAxRfdNWjWD4DWHcu0EWLBLVKMAwRPVtmzWC4TeEcfcmWbBIVKMAwxDVN26RBYtENQowDFF936ZYsEhUowDDENV3bZcFi0Q1CjAMUX3nhlmwSFSjAMMQ1bdumQWLRDUKMAxRfe/GWbBIVKMAwxDVN2+dBYtENQowDFF99xZssEhUowDDENk1broGi0Q1CjAMkV3TtmuwSFSjAMMQ2XVtvAaLRDUKMAyRXdsGbLBIVKMAwxDZ9W20BotENQowDJFN7yZssEhUowDDENl1bskGi0Q1CjAMkV3rpmywSFSjAMMQ2fVuywaLRDUKMAyRXfMmbbBIVKMAwxDZdW/XCIbfEAZOGzaC4TeEgdfGf7BIVKMAwxDdNG3TBotENQowDJFt0+ZZsEhUowDDENU4baAFi0Q1CjAMUY3XFlqwSFSjAMMQ1bht6wiG3xAGzptowSJRjQIMQ1Tjt3USFIhP67z9JygNcU0/0gzEZacFi0Q1CjAMUY3jhlqwSFSjAMMQ1XhuqQWLRDUKMAxRjevWWrBIVKMAwxDV+G6uBYtENQowDFGN8/ZasEhUowDDENV4b9wGi0Q1CjAMkW3jJm6wSFSjAMMQ2XZu1AaLRDUKMAyRbdembbBIVKMAwxDZtm3bBotENQowDJFt33ZusEhUowDDENl2b48Ii0Q1CjAM0U3rNm6wSFSjAMMQ2bZu5AaLRDUKMAyRbe9mbrBIVKMAwxDZNm+GCItENQowDNFN4xcQCc5A/MHiCIrtL5H/HAaJsEhUowDDEN30bv0Hi0Q1CjAM0U3X5n+wSFSjAMMQ3bRthQiLRDUKMAzRTd92iLBIVKMAwxDddG74CIbfEEaO22zBIlGNAgxDVOe00RYsEtUowDBEdV5bbcEiUY0CDENU57bZFiwS1SjAMER1ftttwSJRjQIMQ1TnuOEWLBLVKMAwRHWeG3DBIlGNAgxDVOe6BRcsEtUowDBEdb6bcMEiUY0CDENU57wlFywS1SjAMER13tsoASJRjQIMQ2TsBotENQowDJF929ZusEhUowDDENn3be8Gi0Q1CjAMkX3jhm6wSFSjAMMQ2Tdt6waLRDUKMAyRfddmb7BIVKMAwxDZ9273BotENQowDJF984ZvsEhUowDDENl3b/AGi0Q1CjAMkX3nFm+wSFSjAMMQ2bdupQiLRDUKMAzRXdtmirBIVKMAwxDd9W2nCItENQowDNFd41aLsEhUowDDEN11brYIi0Q1CjAM0V3rZomwSFSjAMMQ3TVtlwiLRDUKMAzRXdcWibBIVKMAwxDdNG+ICYbfEIZemzDCIlGNAgxDdNu08RssEtUowDBENk6bcsEiUY0CDENU67QtFywS1SjAMES1XhtlguE3hKHvJl2wSFSjAMMQ1fpt0wWLRDUKMAxRreMWXbBIVKMAwxDVum3ZBYtENQowDFGt57ZdsEhUowDDENX6bt0Fi0Q1CjAMUa3zpl2wSFSjAMMQ1bpu3gWLRDUKMAxRrfcmqIAQFzIJTjOY4MEiUY0CDENk4zcAAAAAAGEgAAA3AAAAEwRBLBAAAAATAAAABBgBoNwIQCkGlGNAUQYUSJEUArFHAKhYgIllpBsjAEEQBEEQBFEdJMYIQBAEQRAEQRAECXqPJYAgCIIgCMJ7GxIgCIIgCIIgKIIEACMGBhCCYBAOr/A4Ozg8zDJsQATDAOzgADXLBfkdNiACYgB2cJAeZtiACI4B2MFhgphhAyKIBmAFCSpiogtsO2KQLCEIBu0QCwG1NAyGAwEACwAAACYawEgCURnEk++0j5hjwDBIjz0GMBLAPAvSGF9EQAewEM0UYX+wOIICAAAAAAAAAGEgAAA3AAAAEwRBLBAAAAATAAAABBgBoNwIQCkGlGNAUQYUSJEUArFHAKhYgIllpBsjAEEQBEEQBFEdJMYIQBAEQRAEQRAECXqPJYAgCIIgCMJ7GxIgCIIgCIIgKIIEACMGxhKCYBAOr/A4Ozg8zDJsQATDAOzgADXLBfkdNiACYgB2cJAeZtiACI4B2MFhgphhAyKIBmAFCSpiogtsO2KQLCEIBu0QCwG1NAyGAwEACwAAAOYYMAzSY6IBjiQQlUE8+U77iI/YYwAjAcyzII3xRQR0AAvRTBH2B4sjKAAAAAAAAHEgAABnAQAAUg4QImSCpBwgRMjkSDlAiJCh7rwXLAOxEBPBYIP0qNApgmQQ00kxKDU91CQx2CA9lkMUEUFUhWQM1+d0UDNMR4OYabE8LM/XA9QO09FzFzstfoXrdPRbblPUslSMzxCMREz+QyO8j+h4cTzyd51enrvYafHLHW6X9SgcoSkASpoexyIi+y+KBWG+7yAp1QbToVqEyCAmsXmoaQUmgsEG6amIqR2mo+cudlr8Gr/heXn6jKabyDE5zjIhj0EU4KqZnhkNxPXUAmROs+ll+dzFTotf7nC7XDgK0ggihtvwtPtcMgTTCMIaFbQsFeMXi+NEfmUXOq49+wUNsCyOAEwEgw3SYwAGQE2HE1XDZE6z6WX53MVOi1/2snyefrvVx9AAaQiLwQbp0aBMhMggppNixOahJonBBulRKd6PBGmQicEG6bGXYXGMCpCUzykLJC3b0/MyGSTOg6RNS1gGQhIi5JkQp6mDyRiuz+kgYpkdzoOYabE8LM9rU2eChDTSBDQCwS0EEDHYID2GQiiNE+iPpcEVUMgyuBIRic1ERAUgEAw2SI8+rTI0DDEBAzABDDZIT2VA8rK9LBfPXey0+OUOt8tFQwdUGwzUA9HT7TIIlXaD5uXx202ep0D0N4hcHofzIBuMLASl3aB2mkxml0HisJtsJUFtLYFdG5O8bC/LxXMXOy1+2cvyefrttpngVqZ8hA9ppAloBGIlJGJyJSISm4mICkAgGGyQHtUhL2AGQpoiB2OwQXpqYmIeoUzQPU1Hg8r4cRlOT7/dhqFkyASsRPV1p9kEuDrlJlhII01AIxCc00gT0EwSgw3SYyoE1SCTXRANwBBWVBSL40QWI4RZ3bCCUV6O18vucR6EQupToDAddEenx2gQHV0GodNndMssL8frZfc4D6LaYKD0HIQOs80gOroMaqfJZHa5JQ67yac5iGqD1Qc0T5/dYfbcxU6LX+5wu1wwfjCUv+fzt70sB5nl5Xi97B7nQSikPgWal+FheZiedp9B7PcdFHaTQe00mcwug8zycrxedo/T5bkSLSNIBjGh1PRQ0wpMBIMN0lMg0zx9dofZcxc7LX7Zy/J5+u22goH2aXMYbJ8uiagdpqPnLnZa/GKnx2X3vFwjPeEHadP08Fdatp/moLSbXpa7w2wQCATC4XEgY7lMFofHaxCxzA7nQc4y/f6Wr0EoI9GZAplA0zFa/i6Ty3JQmM2Gh+fz1vjdFoPkZXtZLi7Lw/S33AUCTctlEAgEMobrc/ppDpKX7WW5eO5ip8Ug81sOIr/H9XbZTQ/T0283KOwmg+Rlc1ledo/L80KQyGV2OD93sdPil70sn6ff7vKQ5O86vTx3sdPil70sn6ff7mKgjOH6nA4yptn0shzETIvlYXm+SDhtmh7+Sst2UNJNL8vdYTbISHSCpGV7WS42pWECmhrYjOH6nA4ShufpMajILrfLbjqImRbLw/K8IQ2CI1nIURGRhDhNKcCBtGwvy8Ugcrn9BoXhcHZ6HKan326QODwvk0FvNwisT9PDX3nZ/jWT3WCXuRSSACxE1SDNNBkkpdpglkRIUDSVwCMOz9PjuYudFr/c4XZZoaAbGMFhHmoiGGyQniKQxOF5ejx3sdPil70sn6ff7krZA6oNBuqB6Ol2GYRKu0Hz8vjtJs9TIPobRC6Pw3mQDUYWgtJuEPt9b5nl5Xi97B7nQeKwm2wnhTRhC1EUTjtMR89d7LT45Q63y7YSSBo1+BEhjTQBjUCIDTIx2CA9ZRG1w3T03MVOi1/2snyefruNx2CAZXEEXWpHcIQFkCSxQSYGG6RHgRARJIOYWIB5FmIFJoLBBukpg4dcZofzcxc7LX65w+1yaVDGcH1OB0nL9rJcDGKmxfKwPF8dnDFcn9NB0/TZHWaDpO86Pe0+g5hpsTwszwMAAAAA",
					"bitcode_size" : 23744,
					"id" : "obj-19",
					"maxclass" : "newobj",
					"numinlets" : 8,
					"numoutlets" : 8,
					"outlettype" : [ "signal", "signal", "signal", "signal", "signal", "signal", "signal", "signal" ],
					"patching_rect" : [ 418.0, 228.0, 192.0, 22.0 ],
					"serial_number" : "C02Q6FVCG8WP32 bits",
					"sourcecode" : "declare name \"zitaRevFDN\";\ndeclare version \"0.0\";\ndeclare author \"JOS, Revised by RM\";\ndeclare description \"Reverb demo application based on `zita_rev_fdn`.\";\n\nimport(\"stdfaust.lib\");\n\nprocess = dm.zita_rev_fdn_demo;",
					"sourcecode_size" : 216,
					"style" : "",
					"text" : "faustgen~ zita",
					"varname" : "faustgen-7e1a3db8",
					"version" : "1.12"
				}

			}
, 			{
				"box" : 				{
					"comment" : "",
					"id" : "obj-7",
					"maxclass" : "outlet",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 418.0, 339.375, 44.75, 44.75 ],
					"style" : ""
				}

			}
, 			{
				"box" : 				{
					"comment" : "",
					"id" : "obj-6",
					"maxclass" : "inlet",
					"numinlets" : 0,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 492.142853, 53.5, 51.0, 51.0 ],
					"style" : ""
				}

			}
 ],
		"lines" : [ 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 7 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 7 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 6 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 6 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 5 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 5 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 4 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 4 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 3 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 3 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 2 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 2 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 1 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 1 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 0 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 7 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 6 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 5 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 4 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 3 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 2 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 1 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 0 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-7", 0 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-8", 0 ]
				}

			}
 ]
	}

}
