{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 7,
			"minor" : 2,
			"revision" : 1,
			"architecture" : "x86",
			"modernui" : 1
		}
,
		"rect" : [ 909.0, -1001.0, 823.0, 707.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"boxes" : [ 			{
				"box" : 				{
					"id" : "obj-8",
					"maxclass" : "newobj",
					"numinlets" : 8,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 305.0, 323.0, 192.0, 22.0 ],
					"style" : "",
					"text" : "gen~ octoMix"
				}

			}
, 			{
				"box" : 				{
					"bitcode" : "3sAXCwAAAAAUAAAAiEUAAAcAAABCQ8DeNRQAAAUAAABiDDAkSVm+5u3zfi1EATIFAAAAACEMAABYEQAAC4IgAAIAAAATAAAAB4EjkUHIBEkGEDI5kgGEDCUFCBkeBItigBxFAkKSC0LkEDIUOAgYSwoycohIkBQgQ0aIpQAZMkLkSA6QkSPEUEFRgYzhg+WKBDlGBlEYAAAdAAAAG4ggAJYNhPD/////AyBtQIb/////HwA4ACSA2kAQAJBsMAoBWIBqg2EEwAJUG5Dj/////wcADgAJqDYYSAAsALXBSP7///9/ACSA2mAo/////z8AcABIG5BlABJgAaoNCEMACbAA1Qaj+f////8BaANAAgBJGAAACwAAABOEQJggBMMEgRAmBMUEwTgmCMgwIUgmBMMEIVAmBMKEwJgwLIwwQQgaAAAAiSAAAHIAAAAyIsgJIGSFBJMjpIQEkyPjhKGQFBJMjowLhORMEPzDHAGSBwAK5ASABgkBoEJyAOiQBABKJAWAFskAoEbGAOiREQCKZAWAJmkAoEpKAOiSDwDKZAGANrkAoE52AOiTCAAKpWcAgEYpAKBSBgDolDwASmUCgFb5A6BWDgDolTUAimUTgGYjAAQoQs1GtzkCMBgCSEDAAF0CAukSEEKXgAi6HNClgO4eaYooYfIH6WGwQXpQOORyuVwul8vlcrlcLpfL5XK73Y7H4/F4vV6v1/P5fL/f7/f7/X5AIBAIBAKBQCAQCAQCgUAgEAgEAoE6nU6n0+l0Op1Op9PpdDqdTqfT6XQ6nU6n0+koWISakIZzBKBQBFuRjCUQErIMNZuNlKQrRM1mY1KzIDWbjanT6XT0LEbNZmPqdBQtRc3GtNloeo00RZQw+a4ILhSBGttyucQ5nVAoVCqlUrUMNaGVrkXICSlbhpwwR9si6HTULUItR98y1IQ5CheiZrPZaHyPNEWUMPkmMQHgQhFIsJGpXISamc7ELEVNmEunST1HEBSjZgMUc2xqDyMIelCE95vgAwFkIyotCUo4ytF7GIHIg2EEQg9IT+QpAAATrnSYAzywgzYIB3iAB3YohzYgh3CQh3tIB3eIAzhwAztwAzjY0Abl0AbtoAfv0AbwoAdzIAd6MAdy0AbmYAd0oAdzIAd6YAd00AbmgAdwoAdxIAd40AbugAd6EAd2oAdzIAdtMAtxIAd4oPNADBkyUkQEYDDYwoDDcAsDFgMvDHgMvzDgMODCgMkADgMWQy8MuAzjMOAw5MKAzZAOAz6DOgwYDesw4DS8w4DLQA4DJkM4DBgN7DBgNcTDgMtQDgNeAz0MuAzmMGA22MOAw6ALA15DPQy4DfcwYDfsw4DR0A4DTgM8DLgM5zBgMfjCgN/QDwMOwy4MGA3uMOAyoMOA4fAPA4YDSAw4DiEx4Df4w4DlIBIDnsNJDFgN8jDgNuDDgOmAEgNuQz4MWA4jMeA6pMSA5UASA1bDPAyYDOIwYDusxIDvwBIDboM+DFgOJTFgPLTEgOugEgOWg0kMOA8uMWA38MNgyHMHQAAEAgAAAAAAADDkGQUAAAQBAAAAAAAAGPKMAgAAAQAAAAAAAAAMeUwBCIABAAAAAAAAAIY8owAAgCAAAAAAAAAAQx5UAABgAAAAAAAAAIAhzy0AAEAIAAAAAAAAwJAnFwAAKAAAAAAAAABgyJMLAAAYAAAAAAAAADDkyQUAAAwAAAAAAAAAGPLsAgAABgAAAAAAAAAMeXYBAAADAAAAAAAAAIY8vQAEwAEAAAAAAAAAQ55eAALgAAAAAAAAAIAhTy8AAIAAAAAAAAAAwJCnF4AAOAAAAAAAAABgyNMLQAAcAAAAAAAAADDk6QUgAA4AAAAAAAAAGPL8AgAACAAAAAAAAAAMeUYBAIAEAAAAAAAAAIY8owAAQAIAAAAAAAAAQ55wAABAAQAAAAAAAIAhzzkAALAAAAAAAAAAwJBHHQAAYAAAAAAAAABgyBMOAAAoAAAAAAAAADDkCQcAABQAAAAAAAAAGPK0AxAADQAAAAAAAAAMeeABCIADAAAAAAAAACQ+kCkgsUGgMP4DAEAWCAAAAAQBAAAyHpggGRFMkIwJJkfGBEMKrAFQ0+FENFBJ+ZyyQNKyPT0vk0HiPEjaVEkcnqfHcxc7LX7Zy/J5+u1WiVxmh/NzFzstftnL8nn67VbJGK7P6aBmmI4GMdNieVieV0n+rtPLcxc7LX7Zy/J5+u2mgj7i8Dw9nrvYafHLHW6X9SGX2eH83MVOi1/ucLusj/xdp5fnLnZa/HKH22U66GYM1+d0kDA8T49BRXa5XXbTQcy0WB6W5ymxA+3TO9g+vcPiGLTQyRiuz+kgYpkdzoOYabE8LM/rZE6z6WX53MVOi1/2snyefrt1aofp6LmLnRa/xm94Xp4+o+k6MY9QJuiepqNBZfy4DKen326d5GV7WS6eu9hp8ctels/Tb7dO8/TZHWbPXey0+GUvy+fpt5sauwyEJETIMyFOQw+FA2nZXpaLQeRy+w0Kw+Hs9DhMT7/dIHF4XiaD3m4QWJ+mh7/ysv1rJrvBLoooZE6z6WX53MVOi1/ucLusUDtMR89d7LT4Fa7T0W+5QvKyvSwXz13stPjlDrfLCs3TZ3eYPXex0+KXO9wu00QpY7g+p4OMaTa9LAcx02J5WJ5Xyhiuz+kgadlelotBzLRYHpbnqbIFuGqmt4U0YQuxhSQAC0EXjdphOnruYqfFL3Z6XHbPyxq1w3T03MVOi1/2snyefrspo047TEfPXey0+OUOt8u0WaIBGGIJpXGCJagGmZRgGkFY6qySIROwEtXXnaogjSBiuA1Pu8/0Uc4Yrs/poGn67A6zQdJ3nZ52n0HMtFgelueV06bp4a+0bAcl3fSy3B1mg4xEJ0hatpflYgrtURGRhDjNHpPjLBPy0Eh7wg/Spunhr7RsP81BaTe9LHeH2SAQCITD40DGcpksDo/XIGKZHc6DnGX6/S1fg1BGojMFMoGmY7T8XSaX5aAwmw0Pz+et8bstBsnL9rJcXJaH6W+5CwSalssgEAhkDNfn9NMcJC/by3Lx3MVOi0HmtxxEfo/r7bKbHqan325Q2E0GycvmsrzsHpfnVNqg3kDawN7g3gCn0wgApXQPqDYYqAeip9tlECrtBs3L47ebPE+B6G8QuTwO50E2GFkISrtB7Pe9ZZaX4/Wye5wHicNuMq0UYb7vICnVBlOkmSaDpFQbjFrqB0P5ez5/28tykFlejtfL7nEehELqU6B5GR6Wh+lp9xnEft9BYTcZ1E6TyewyyCwvx+tl9zhdntNrhTCjmNIB1QYD9UD0dLsMQqXdoHl5/HaT5ykQ/Q0il8fhPMgGIwtBaTeonSaT2WWQOOwm00xZwSgvx+tl9zgPQiH1KVCYDrqj02M0iI4ug9DpM7pllpfj9bJ7nAdRbTBQeg5Ch9lmEB1dBrXTZDK73BKH3eTTHES1wQAAALEYAABWAAAAMwiAHMThHGYUAT2IQziEw4xCgAd5eAdzmHEM5gAP7RAO9IAOMwxCHsLBHc6hHGYwBT2IQziEgxvMAz3IQz2MAz3MeIx0cAd7CAd5SIdwcAd6cAN2eIdwIIcZzBEO7JAO4TAPbjAP4/AO8FAOMxDEHd4hHNghHcJhHmYwiTu8gzvQQzm0Azy8gzyEAzvM8BR2YAd7aAc3aIdyaAc3gIdwkIdwYAd2KAd2+AV2eId3gIdfCIdxGIdymId5mIEs7vAO7uAO9cAO7DADYsihHOShHMyhHOShHNxhHMohHMSBHcphBtaQQznIQzmYQznIQzm4wziUQziIAzuUwy+8gzz8gjvUAzuwwwzHaYdwWIdycIN0aAd4YId0GId0oIcZzlMP7gAP8lAO5JAO40AP4SAO7FAOMyAoHdzBHsJBHtIhHNyBHtzgHOThHeoBHmYYUTiwQzqcgzsAAACpGAAABgAAAAsKciiHd4AHelhwmEM9uMM4sEM50AMAAGEgAAAJAAAAEwQBhgMBAAAFAAAA5hgwDNJzAAvRTBH2B4sjKAAAAAAAAAAAYSAAAAoAAAATBMEFth0xKIAQBIM7uIUAw4EAAAMAAAAHUBDNFGHmGDAM0gMAAAAAYSAAAAkAAAATBAGGAwEAAAUAAADmGDAM0nMAC9FMEfYHiyMoAAAAAAAAAABhIAAADgAAABMEQSwQAAAAAgAAAFQsQHhUAwAAIwYFEIJgYAqzEFwg3AzCgQAAAAACAAAAB1AQzRRhAAAAAAAAYSAAAPAAAAATBEEsEAAAAGwAAACUK4RyDCjFgKIMKIeCDCiCwhgBINtQxxiQwRjkAU7kAU4MdXxgQAZ5gBN5gBNDHWVgBmWQBziRBzgx1JEGapAGeYATeYATQx1rwAZskAc4kQc4MdRRBmbQBnmAE3mAE0MdbeAGcJAHOJEHODHUsXFykAc4kQc4MdRRBmYwB3mAE3mAE0MdcSAHdJAHOJEHODHUsQZsUAd5gBN5gBNDHWVgBnaQBziRBzgx1DEHdHAHeYATeYATQx2dhwd5gBN5gBNDHW8AB3GQBziRBzgx1FEGZrAGeYATeYATQx2J8gZ5gBN5gBNDHZXlBnmAE3mAE0MdG6cGeYATeYATQx0bhwZ5gBN5gBNDHZV1BnmAE3mAE0MdZ4AGZpAHOJEHODHUEQZiIAZ5gBN5gBOkGyMAQRAEQRAEQf4fxghAEARBEARBEAWJMQKdNeecNeecdf9hjAAEQRAEQRAERZAYIwBBEARBEARRHSTGCEAQBEEQBEFUBokxAhAEQRAEQVAfQ2KMAARBEARBEARBkBgjAEEQBEEQhPc2JMYIQBAEQRAE4b0MiTECEARBEARB/K5DgpgjAADXBvOlwDZ2dXgDMzgDCqhjxAABQhAMZiEYiugMdnWIAzRQAwqWY8TAAEIQDFQhKNCACOrYwaEO1sANRgwQIATBYBaEI0gDiwzqGDFAgBAEg1kIEAHL6KCOEQMECEEwmIUgGS41IIQ6RgwQIATBYBYCheC+XR3w4A3mgALoGDFYgBAEg1cIGDYwrAy7aKGOHRz4QA7uYMQAAUIQDGZBcII26KihjhEDBAhBMJiF4BHEYAzIoY4RAwQIQTCYhQAawCAM6KGOEQMECEEwmIUgIr43IIg6RgwQIATBYBYCqSADNCAEOkYMFiAEweAVggkODG7TwIAk6tjBYRTy4A9GDBAgBMFgFoQqiAMyIIo6RgwQIATBYBYCS0gDNaCKOkYMECAEwWAWgms4AzQgizpGDBAgBMFgFgKMMIM5oIs6RgwQIATBYBaCrFgDN6AHOkYMFiAEweAVAo0ODDA4AzMoA8qoYwcHVQCFUxgxQIAQBINZELigDtaANuoYMUCAEASDWQg6AQ7igDjqGDFAgBAEg1kIvMEN3oA66hgxQIAQBINZCD6iDe6APOoYMUCAEASDWQjAoJADOyALOkYMFiAEweAVgjDAA8MMyoAM3GBXh1cwBVegADdGDAogBMHgDoIxwHAgAAAABgAAAPYYkCDNREQFIBAHQCANMpljwDBIDwAAAAAAAABhIAAADwAAABMEQSwQAAAAAgAAAJQbASgRAAAAOzgMQkBBbmQQDgQABQAAAOYYMAzScwAL0UwR9geLIygAAAAAAAAAAGEgAAAMAAAAEwRBLBAAAAABAAAAlCsIABmEAwEFAAAA5hgwDNJzAAvRTBH2B4sjKAAAAAAAAAAAYSAAAAwAAAATBEEsEAAAAAEAAACUKwgAGYQDAQUAAADmGDAM0nMAC9FMEfYHiyMoAAAAAAAAAABhIAAAFAAAABMEQSwQAAAAAgAAAJQriBKoAQAAww3EQAbTDYMQZBAOBAAAAAkAAADmGDAM0mOPAYdwAE1DLAewEM0UYX+wOIJilAFGREwVsAAAAAAAAAAAYSAAABQAAAATBEEsEAAAAAIAAACUK4gSqAEAAMMNxEAG0w2DEGQQDgQAAAAJAAAA5hgwDNJjjwGHcABNQywHsBDNFGF/sDiCYpQBRkRMFbAAAAAAAAAAAGEgAAAKAAAAEwSBBYF8MggHAgAABQAAAAewEM0UYX+wOIJijgFFBSwUAQAAAAAAAGEgAAAKAAAAEwQBhgMBAAAGAAAA5hjASADzLEhjfBEBHcBCNFOE/cHiCAoAAAAAAGEgAAAiAAAAEwRBLBAAAAAPAAAAlBsBKMWAcgwoygDSjRGAIAiCIAiCIAgSYwQgCIIgCIIgqoMEvccSQBAEQRAE4b0NCRAEQRAEQRAUQQIAOzgghzFsQATEAOzgkCDGBfkdNiACYgB2cFiUY9iACIwBwHAgBQAAAOYYMAzScwAL0UwR9geLIygAAAAAAAAAAGEgAAAaAAAAEwRBLBAAAAAFAAAABBgBoNwIQIEUSSFQsQATy4g9AgA7OCBGMWxABMcArCCRHMVxgW1HDBIgBMGgHUwhUAqDwHAgAAAHAAAA5hgwDNJjlwGKJBCVQTz5Th/AQjRThP3B4ggKAAAAAABhIAAAbQEAABMEQSwQAAAAcgAAAJQbASiBGYAiKIPy/yv/jxIpwoAyDCjEgGIMKMmAsgwozYDiDCiMAg0o0YCyKIoyDSjUgGINKNeAYijZgKINKIVCKNuAwg0o3YDyDSjgANKPRfzf/z//H/z/Mxbx/8H/P//3/8dYBBAIxRwETNDETMjEHIRMxIRMyMRYxP8H/3/83/8fYxFAIRxjEUAgEHMQMCETMiETpBsjiEE8fW98f3nxH8YIdLSEZ3YH3Vv+hzGCVn9T0rdd/z3/YYwAFeHYzXceHul/GCMA+fo1z/WnefIf6D2WAIIgCIIgCIL4P4AgCIIgCIIg/g8zAGMJJ7jXZj7LtVn+AzvSb/ruPy/H/zCWYO80zdc1Se/lP8QgiMd97vMi/A9jCWXew62Ys26I/gMIgiAIgiAIwv8wh8AXrjGWkPfqW6OmHqLmP5C1yf59yvak/A9jCfEKwqaql/1v/oN9iuocpjUazv9AujECHF1RUm3/MBVBYowAR1eUVNs/TE2QGCMocTvGZ/bOefgfxghAEARBEAThPRSJMQIQBEEQBEEQ5P9hBmCMAARBEARBEATxfxgjAEEQBEEQBEH+X8YIwv7/cVaNw94EGdrPQcCGa7iGa8wAADs4mAIp9MGwARGYwgCcKehsOCJIiG+6QRGC4YiAEb7phkYIdnBgBVUQhWEDIhAGwARIPhY08BkxMIAQBIuvF3Ai2MEBFlyhFIYNiEAYABMc+Vhw0GcHh1mIhVMYNiACYQAMS+izg0MtzAIqDBsQgTAAti302cHhFmohFYYNiEAYgB0ccMEWUmGOoQycW5hjCJ5bsMAM5GNBGsBnxKAAQhAM4OEmgkGGQA3iYAxB6IUxhKEXLsnvsAERFANgwicfCzD67OBADuJAC8MGRCAMwA4O5TAOtGAMHMjHAjqAz4hBAYQgGMCDWARjCME5zDGUQYAOcwzBgg5zDEFzDnMMgXcOcwxqUKzDHEPQBuowyBBIpGBEAB8rhPgMMggBKlygpwpWQXdwsAd6IIcL+DtsQATDANyU32EDIogGYAwhsgcL7kA+FsABfXZw4Ad9SIdhAyIQBmAHh37Yh3QwMjgF+VjACvAZMSiAEAQDeNCLYJAhaAVcGEMQQGIMYQAJW4T4XJCjCv5Bd3A4iZKQh2EDIhAGwAxTgM8FOapAJHQHh5VIiXoYNiACYQDuye+wARE0A2CKKsjHglGgzw4OL9ES+DBsQATCAOzgABMugQ9zDLlgCi4xx5AH4/ASJgTysSAc4DNiUAAhCAbw8BrBIEMgDukwhiDQxCH5HTYgAmIATLAF+VjwCvTZwWEnckIkhg2IQBiAHRx4QidEwkaBHORjwTrAZ8SgAEIQDOAhN4IxhMAnBhkEJh8GGYIw2Ic5hl8YwGKOIRCHnxhkCJ58sICAjxVCfAYZhKAfLtBTBSShOzisRVrAxAX8HTYggmEALsrvsAERPAMwhvCshQXsIB8LyoE+OzjExVvUxLABEQgDYOcgEvKxQB7gM2JgACEIFl8v9Eewg0NdzAVODBsQgTAAhgjxuSBHFcSF7uCQF3exE8MGRCAMgBn4AJ8LclQBXegODn2xFz4xbEAEwgDYPLSEfCzwB/iMGBhACILF1wspEuzgEBp/ERbDBkQgDIAJ/yAfC/CBPjs4kIZojMWwAREIA7CDQ2mMxlgYO7CEfCygCfiMGBRACIIBPIhIMMgQ1ARPjCEIqDGGMKDGHfkdNiCCYgBMUAn5WDAS9NnB4TVagy2GDYhAGAArCZ+QjwUwAZ8RAwMIQbD4emFHgh0cZiM23mLYgAiEAZhjeAlBNuYYAkU25hgCJjbmGIIrNuYYaMKojTmG4CZoY5AhiNzCiAA+VgjxGWQQArm4QE8V6IUeePB32IAIhAHAcCAIAAAA5hgwDNJjjwGMBDDPgjTGFxHQASxEM0XYHyyOoAAAAAAAAAAAYSAAAKMAAAATBEEsEAAAAFoAAACUK4ERALINdVQWlAcwkQcwMdTxgUGXBzCRBzAx1BEIQB7ARB7AxFDHQAR5ABN5ABNDHYUh5AFM5AFMDHUcyJAHMJEHMDHUMRBEHsBEHsDEUEdhGHkAE3kAE0MdC3PkAUzkAUwMdQwEkgcwkQcwMdTROEkewEQewMRQxwMpeQATeQATQx2RtOQBTOQBTAx1TBSTBzCRBzAx1LEwTR7ARB7AxFBHJD15ABN5ABNDHQsT5QFM5AFMDHVcmJQHMJEHMDHUsTBTHsBEHsDEUEemUXkAE3kAE0MdA1HlAUzkAUwMdVyYlQcwkQcwMdSxcVcewEQewMRQR+dheQATeQATQx2RlOUBTOQBTAx1TJSWBzCRBzAx1LEwWx7ARB7AxFBHYXB5ABN5ABNDHQPh5QFM5AFMDHVE0pcHMJEHMDHUsTBgkAcwkQcwMdQRBmIQBnkAE3kAE0MdieLkAUzkAUwMdSRKkQcwkQcwAQBXBvOlwDZWeTiDMjADCshjxOAAQhAMxiEYyGAMRgwOIATBYByCQQzCYMTgAEIQDMYhGMCgGDE4gBAEg3EIhs8bMTiAEASDcQiGrhgxOIAQBINxCAZuGzE4gBAEg3EIBi0bMTiAEASDcQgGzBgxOIAQBINxCIbLDEYMDiAEwWAcgsEygxGDAwhBMBiHYKioEYMDCEEwGIdgmKQRgwMIQTAYh2CIjBGDAwhBMBiHYICeEYMDCEEwGIdgcJoRgwMIQTAYh2BgihGDAwhBMBiHYFjKYMTgAEIQDMYhGJRixOAAQhAMxiEYkjIYMTiAEASDcQgGpBgxOIAQBINxCIajwHAgBAAAAAewEM0UYX+wOIJijgEBAwAAAAAAYSAAALcIAAATBEQsEAAAAG8AAACUGwEogfL/K/+P8n8o//+AIiiEgimgwimUMiiFYiiHIiqQUimfAhcsK5aiKUDBsnIpmwIeLCvowLIiKcjBspIpnTIpnoIfLCuhggwsK+DAsoIPLCtowbICHCwr2MGyAh8sK8WAQgwoxoByDCjIgJIMKMqA0gwo0IAyDSjWgJINKNyA8g0oqrIqSMKygiUsK7wCJywruIImLCvAwrKCFywreMKyAi0sK8jCskIr4MKyAivYwrICLywrSMGygi4sK0DDsoIvLCvAgMIqUMOygipIw7ICNiwr6MGygjUsK3DDsoI2LCukAjwsK3jDsgI9LCvwwLKCPCwr4MOygj0sK/DDsoI+LCtAxLICHSwr+MOyAkUsK0jEsgJGLCtYxLKCFSwrYMGyAkcsK2jEsgJMLCt4xLLCKNDEsoIoyMSyAiQsK+DEsoJNLCvwxLKCTiwrQMWygk8sK1DBsgIlLCtgwrICDSwj3RgBCIIgCIIgCPL/MEYAgiAIgiAIgvy/jACMEcw5a845a845/g9jBKzv+uecz2Bd/8MYwRjDZGqSNM/H9zBGMOesOeesOef4v4wRgCAIgiAIgiAIIgAAAACUEsyxmYJKnAQFzLGZAkuQBAXMsZmCS4AEBcyxmQJMnAQFzLGZgkyMBAXMsZkCTZAEBcyxmYJNlAQFzEE3wRybKeCETVDAHJsp6MRMUMAcmynwxEtQwBybKfiETVDAHJspgIVMUMAcmymIxUxQwBybKZAFTVDAHDs4pEVZ6AMFurGDw1qcxT5QoBsWDPQZMTCAEASLrxfsI7AgkM8ODnDBFv9AgW7s4CAXbgESFOiGBYN8RgwMIATB4uuF/QgsOORjdBDEx+ogiY8JgnxMEORjQkAfC/AAPsMRAR4Q33RDHgjBiIEBhCBYfL1AIoElCH1M8AP4WCDEx4JKPjs4kAZoxAQFumFaQJ8RAwMIQbD4euFFAgs0+lhQCvDZwUE1TMMmKNCNHRxYAzVuggLdsGCQz4iBAYQgWHy9MCOBtUJAHwtcAT72CkJ8LBDoY6oQxMdkgaCPWVd8dnC4jdkICwp0w4I3oM+IgQGEIFh8vSAmgQWBfCw4A/mYLgTxsV0Y4mOCIB8TBPmYENDHAl+Az3BE4AvEN93wC0IwYmAAIQgWXy+oSWAJQh8TyAE+FgjxseCRj0llQJ8RAwMIQbD4emFOAgsk+liQDvAxJInPDg7vsR54QYFuWHAK9BkxMIAQBIuvF/QksCCQjwV/IB+ThyA+Ng9DfEwQ5GOCIB8TAvpYYA/wGY4I7IH4phvuQQhGDAwgBMHi6wVRCSxB6GMCP8DHAiE+FjzyMakP6DNiYAAhCBZfL6xKYIFEHwtCAj6GJPHZweFERuQ1KNANC36BPiMGBhCCYPH1gqwEFgTyseAW5GMqEcTHVmKIjwmCfEwQ5GNCQB8LXAI+wxGBSxDfdMNLCMGIgQGEIFh8vaArgSUIfUygCfhYIMTHgkc+JtUCfUYMDCAEweLrhXEJLJDoY0FOwMeQJD47OPzIjpgHBbphwT3QZ8TAAEIQLL5eUJfAgkA+FryDfEwsgvjYWAzxMUGQjwmCfEwI6GOBWcBnOCIwC+KbbjgLIRgxMIAQBIuvF+QlsAShjwlsAR8LhPhY8MjHpHagz4iBAYQgWHy9sC+BBRJ9LIgL+BiSxGcHhzuZk/6gQDcseAn6jBgYQAiCxdcLIhNYEMjHgpOQj+lFEB/biyE+JgjyMUGQjwkBfSzwC/gMRwR+QXzTDX8hBCMGBhCCYPH1gsoEliD0MYE04GOBEB8LHvmYVBL0GTEwgBAEi68XZiawQKKPBakBH0OS+Ozg8CqrQiMU6IYFZ0GfEQMDCEGw+HpBZwILAvlY8BPyMdkI4mOzMcTHhIA+NgzysWGQjwkBfSy4DfgMRwS3QXzTDbghBCMGBhCCYPH1wtgEhgTxMaE34GOBEh8LIPnY5BP0GTEwgBAEi68X2CawYKKPBeIBnx0czmVc1oQC3bDgL+gzYmAAIQgWXy/ITWBBIB8L7kI+ph5BfGw9hviYENDHhkE+NgzyMSGgjwXvAZ/hiOA9iG+6AT6EYMTAAEIQLL5e2JvAkCA+JtQHfCxQ4mMBJB+b7II+IwYGEIJg8fUC6QQWTPSxQD/gM9zgL/tiBrMMwRDsIAEy/DIq+7KDRMj0S7vwyw4SIuMv7oIvO0iMzL+Uir/s4EAyIPMuVOgGFbpBhW5QoRtU5MYsgTBQkQdCsKeBMFChB0bwpoEwUKEHSvC6gTBQoQdOsLqBMFChB1IQpoEwUJEHNhaUbiAczODXhr6QjxUGfCzwC/lYMMDnaiaXFdwKXMDUYQMiIAbAiNeQjwUMfOw2AvkYVBryMSGAz/VMLivwFbiAqcMGREAMQFk6oztIhE3PrExgxo7Ix4Idgc+wATEEA7B0Qo5UFOjGmU0uKzAXuACvFORGgUEQFZSN7iDBNmhjMwEFumFJAJ97m1xW4C5wAVMp0A0L2kQ+ZgTxqTVoG91Bwm7k5meCYQMiGAbg7iaXFdQLXIBXCnKj4iCICuhGd5Dom7wxm4AC3bi/yWUF/AIXMHXYgAiIATCHT+RDkm5YIMDnSieXFYQMXMBUCnTDgvqQz6lOLiuYG7iAqRToxrlOLitIGbiAqRTohgUFfCzwD/lYsMDnaieXFbwMXMDUYQMiIAbAiPWQjwUMfCw+Avnc7uSyApqBC5hKgW5YEB/yMSOAz4VPLivIGbiAqcMGREAMwA4S5AM+q0MKVviKfCzwFfgMGxBDMABLJ9AKLlCgG5c+uawAbOACvFKQGzUOQVSAPrqDxPusj+0EFOiGJQF8Tn5yWQHawAVMpUA3LIAX+ZgRxKfcIX50B4n8qZ/fCYYNiGAYgNOfXFbwNnABXinIjaKHICrAH91BAoT4x3wCCnTjRCiXFdgNXMDUYQMiIAbAnH+RjwWiAB+adMOEAD6XQrmsgG/gAqZSoBsW5Il8zoVyWQH9wAVMpUA3ToZyWQHpwAVMpUA3LCjgY4GoyMeCBT6XQ7msQHXgAqYOGxABMQBG3Ih8LGDgYz0SyOd+KJcVvA5cwFQKdMOCHpGPGQF8roxyWQHtwAVMHTYgAmIADo1yWYHtwAV4pSA3KjAj3UGijdIohgJTzkY+FpwNfIYNiCEYgKUTwiYsKNCNk6NcVvA7cAFeKciNWoKoII50Bwk8oiMeCijQDUsC+Nwe5bKC84ELmEqBbliQN/IxI4hPWXqkO0iIkh+VUTBsQATDANwo5bIC94EL8EpBbhQXRAWhpDtIpFIpsVFAgW7cKuWygvqBC5g6bEAExACYgzryuVfKZQX4AxcwlQLdsOBf5HO0lMsK7gguYCoFunG4lMsKQAguYCoFumFBAR8LUEY+FizwuV/KZQUmBBcwddiACIgBMKJU5GMBAx9blUA+V065rGCF4AKmUqAbFqyKfMwI4HPrlMsKYAguYOqwAREQA7CDhDupkziJghXoIx8L0Ac+wwbEEAzA0gm6Ix4U6MbNUy4ruCG4AK8U5EaxQhAVyJPuIJFP9dROAQW6YUkAn+OnXFbwQ3ABUynQDQv0Rz5mBPGpW9An3UFipP7JnoJhAyIYBuBIKpcV4BNcgFcKcqN6IYgKQkp3kFApk+qngALdOJbKZQVuBBcwddiACIgBMCeF5GOigBLwIVrQDaJ0wwYCPhYM8LFggM/ZVC4ruCO4gKkU6IYFpiOf26lcVtBPcAFTKdCN+6lcVvBHcAFTKdANCwr4WPA68rFggc+ZVS4rKCW4gKnDBkRADIAR9CIfCxj4mL4E8jm2ymUFqgQXMJUC3bBAX+RjRgCfk6tcVvBKcAFThw2IgBiAUgm20h0k7EqubCowA47kYwEcwWfYgBiCAVg6gY3UhALduL3KZQVuBRfglYLcKJoIooK70h0kQquvwiqgQDcsSOBzpJXLCsAJLmAqBbphgSjJx4wAPjtIqJZp8VVKDBsQgTAAFBa5cayVywpCCy7AKwW5UUUQFaiW7iAhW65FWgEFunG0lcsK3gkuYOqwAREQA2COK8nncCuXFcgTXMBUCnTDAhSSz/VWLivoK7iAqRToxoVXLivQJ7iAqRTohgUFfCyIIflYsMDn0CuXFYAUXMDUYQMiIAbACJ+RjwUMfIxsAvmce+WygpKCC5hKgW5YQDbyMSOAz9FXLitQKbiAqcMGREAMQLFBfOkOEvhFX7YVmCFP8rFAnuAzbEAMwQAsnWBO7EKBblx/5bKC94IL8EpBbpQdBFEBf+kOEiP2X+EVUKAbFiTwORPLZQU7BRcwlQLdsICk5GNGAJ8KhRLTHSRaLMXUKxg2IIJhAM7FclmBfsEFeKUgN+oUgqiAxXQHCRqDsfgKKNCNs7FcVqBWcAFThw2IgBgAc2BKPqdjuaygreACplKgG+djuawAruACplKgGxYU8LHAleRzZJbLCuoKLmAqBbphAS3Jx4wAPqdmuaxAr+ACpg4bEAExANdmuayAr+ACplKgGxbIjnwsYR35WGDBx2QnkI8FBHzOznJZAWnBBUwdNiACYgDKHeBMd5DQMzuzscAMupKPBXQFn2EDYggGYOkEtnIbCnTj/iyXFbAWXIBXCnKj8CGICvZMd5AotVALs4AC3bAggc+hWi4roC24gKkU6IYFpiUfMwL47CDhaqqWZqIwbEAEwgDcq+WyAt2CC/BKQW4USgRRQavpDhK1FmtwFlCgG3druawgvOACpg4bEAExANbElnxu13JZgZ3BBUylQDfu13JZAXrBBUylQDcsKOBjwUvJ58otlxW0F1zAVAp0w4Kako8ZAXxu3XJZgXzBBUwdNiACYgDO3XJZAX3BBUylQDcs2B/5WFI/8rHAgo/tTyAfCwj43L3lsgL+gguYOmxABMQAEKzkRgXypjtI8Bu+tVtgh33JxwL7gs+wATEEA7B0gnnBDwW6cSGXywpKDC5gKgW6YcF/yccCAz53crmsoN/gArxSkBsVBVHByOkOEi2Xcv4WUKAblgTwKQvldAeJmGs5dQuGDYhgGAASodyoLIgKWE53kKi5mHO3gALduJvLZQU6BhcwddiACIgBsCXG5GOkYSLwIdvQDaoJ3aBNN6gWdMOKk4CPBacAHwsQ+FhwwMeCAz4WHPCx4IDPnV0uKwA5uICpwwZEQAyA1chsxMcCmYiPBbIQHwum+FggxccCKT4WSPGxQIrPyV0uK1A5uICpwwZEQAwA4YtuEJ7ohtnJvcDHAjmTjxEBfCwg4GPkMTfwsWAs4GPBOMTHAjKIjwVjAB8LxgA+FoxBfCwYg/hYkMTnSC+XFewcXMDUYQMiIAbA/gY+4mPBW8THgneAjwVwAB8L3iA+FrxBfCx4A/hY8AbwsaCKz8FeLiuQNbiAqcMGREAMgJXMC8HHgg8+FD66YUHswMfCAFXgY0IAH4MR14iPtUQAHwtYIT4WzJp8LBQC+FgQCvGxIBTiY0EowMeCBj4WKPG58ctlBXkHFzB12IAIiAGw3eiR+FigE/GxIBfgYwG4yccCV4iPBa4AHwtcAT4WuEJ8LNDgY8EVn4O/XFZQenABU4cNiIAYACOXN4KPBX4AHwOFs4GPgUEAH/PUIj4WpAN8LIA3+ZgvBPCxwBfiY4EvwMcCX4iPBQp8LEjicyAY5LIC2oMLmDpsQATEAJhddPCxoB7iYwG/yccCdYiPBeoAHwvUIT4WqAN8LLDgY0EVn2PBIJcV/B5cwNRhAyIgBmDphHoDqWEDIlCHASBe0I2lE+pNpIYNiEAYAGIF3Vg6od5IatiACIQBIFHQjaUT6s2khg2IQBgAigPdWDqh3lBq2IAIhAEgM9CNpRPqTaWGDYhAGADCdGPphHpjqWEDIhAGgBzdWDqh3lxq2IAIhAGgk9KN+8EglxWAHVzA1GEDIiAGgEZKN24Mg1xWMHZwAVOHDYiAGADin9yoQAwDGDYg/CcYADon3Rg2IPApGACSJd0YNiDGKRgAOiXdGDYgXCkYADoj3Rg2IPAoGACKId0YNiDEKBgAMiHdGDYgWigYAAof3Rg2IOQnGAByHd0YNiB+JxgAGh3dGDYgVCcYABob3Rg2IOgmGABSGd0YNiB2JhgA+hfdGDYgTCYYAPIV3Rg2IN4lGABaFd0YNiB4JRgAAhXdGDYgTiUYAPoR3Rg2IOAkGABiEd0YNiBmJBgAChHdGDYgViQYAAoP3Rg2IOIjGAByDd0YNiBqIxgAGg3dGDYgWiMYACIL3Rg2IPYiGIDzwyCXFdxgABfklYL3OFEMcllB6MEFeR02IAJiAK4Ug1xW0IMBXJBXCt7jUjHIZQVrGMAFeR02IAJiAI4Vg1xWMIYBXJBXCt7jYDHIZQV2GMAFeR02IAJiAOhOdGPYgKCTYABIJHRj2IDIk2AArhaDXFawhgFckFcK3uNyMchlBaIYwAV5HTYgAmIAjheDXFYQhwFckFcK3uPAMchlBaAYwAV5HTYgAmIAbhyDXFZwhwFckFcK3uPOMchlBaoYwAV5HTYgAmIATh2DXFbQhwFckFcK3uPcMchlBakYwAV5HTYgAmIATLzYMYDBGEIcuGMwhiAH7hgMN8xjMIDBLMMgBBgOBADhAwAARpmA+A1h6Dt+22NAIThUM5ljwDBIj00SEP4TEQYZYCDNQ02S3RMsEtUowDBENU0bPsEiUY0CDENU07XlEywS1SjAMEQ1bRtgwSJRjQIMQ1TTuAUWLBLVKMAwRDWdm2DBIlGNAgxDVNO7IRYsEtUowDBENc1bYsEiUY0CDENU17QpFiwS1SjAMER1XRtkwSJRjQIMQ1TXtkUWLBLVKMAwRHV9m2TBIlGNAgxDVNe4XRYsEtUowDBEda0bZsEiUY0CDENU17tlFiwS1SjAMER13RslgeE/EaH3RmqwSFSjAMMQ2TRtnAWLRDUKMAxRbdPWWbBIVKMAwxDVtm2eBYtENQowDFFt3xZasEhUowDDENV2bqIFi0Q1CjAMUW3rZmqwSFSjAMMQ2fRtpwWLRDUKMAxRbfMGWrBIVKMAwxDVNm6tBotENQowDJFN94ZasEhUowDDENV2b5UEhv9ExE6bJYHhPxGx13ZJYPhPROy2rRosEtUowDBENr1bqsEiUY0CDENk07ipGiwS1SjAMEQ2rVupwSJRjQIMQ2TTtbkaLBLVKMAwRHZNW2rBIlGNAgxDVN+0tRYsEtUowDBE9V2ba8EiUY0CDENU37a9FiwS1SjAMET1jdtswSJRjQIMQ1Tfub0aLBLVKMAwRHZtW23BIlGNAgxDVN+87RosEtUowDBEdt0brcEiUY0CDENk17fVGiwS1SjAMER2nZutwSJRjQIMQ2TXutEWLBLVKMAwRPW9m67BIlGNAgxDZNe8zR4sEtUowDBEN02bbcEiUY0CDENU47TdFiwS1SjAMEQ1XhtuwSJRjQIMQ1TjtgEXLBLVKMAwRDV+W3DBIlGNAgxDVOO4dRIUiE/rvAkXLBLVKMAwRDWuW3LBIlGNAgxDVOO7KRcsEtUowDBENd4br8EiUY0CDENk27UlGywS1SjAMES2vVuwwSJRjQIMQ2TbuAkbLBLVKMAwRLadG7DBIlGNAgxDZNu28R4sEtUowDBEN91b7sEiUY0CDEN007npHiwS1SjAMEQ3rRvtwSJRjQIMQ3TTtikbLBLVKMAwRLbNX0AkOAPxB4sjKLa/RP5zGO7BIlGNAgxDdNO3LRssEtUowDBE9k0b8cEiUY0CDEN017YtFywS1SjAMER1Tlt0wSJRjQIMQ1TntkkXLBLVKMAwRHV+W/PBIlGNAgxDdNe7TRcsEtUowDBEdZ5bdsEiUY0CDENU57ppFywS1SjAMER1vtt2wSJRjQIMQ1TnvHUXLBLVKMAwRHXeG7XBIlGNAgxDZN+4cRssEtUowDBE9t2btsEiUY0CDENk37pNGywS1SjAMET2fZvxwSJRjQIMQ3TXufUeLBLVKMAwRHddm7TBIlGNAgxDZN+1FR8sEtUowDBEd43btsEiUY0CDENk37vtHiwS1SjAMEQ3zVt0wiJRjQIMQ4TTtD0fLBLVKMAwRLdNm/XBIlGNAgxDdNu1TScsEtUowDBEOG3b9cEiUY0CDEN027eRGywS1SjAMEQ2fht1wiJRjQIMQ4TTt3UfLBLVKMAwRLet27nBIlGNAgxDZOO6YScsEtUowDBEOK0busEiUY0CDENk47ytGywS1SjAMEQ23tt2wiJRjQIMQ4TTvX0fLBLVKMAwRLfdm/fBIlGNAgxDdNu7YR8sEtUowDBEt42beMEiUY0CDENU67eJGywS1SjAMEQ2TtsogSJRjQIMQ6TXRkqgSFSjAMMQ6baVEigS1SjAMET6basEikQ1CjAMkY4bK4EiUY0CDEOk59ZKoEhUowDDEOm60RIoEtUowDBE+m61BIpENQowDJHOmy2BIlGNAgxDpPc2XrBIVKMAwxDVOm7kBYtENQowDFGt5+Z8sEhUowDDEN01b94Fi0Q1CjAMUa3X9l2wSFSjAMMQ1bpt5QeLRDUKMAzRfdOWnbBIVKMAwxDh9G7oBYtENQowDFG909ZesEhUowDDENV7be4Fi0Q1CjAMUb3f9l6wSFSjAMMQ1Ttu8wWLRDUKMAxRvedGX7BIVKMAwxDVu271BYtENQowDFG97wewEM0UYX+wOIJi+QWLRDUKMAxRvffGbrBIVKMAwxDZeW3jCYtENQowDBFe4/ZusEhUowDDENk5bucJi0Q1CjAMEV7vBp6wSFSjAMMQ4fVtvQSKRDUKMAzRTpsvgSJRjQIMQ7TX9kugSFSjAMMQ7bYVEygS1SjAMET7bccEikQ1CjAM0Z6bMYEiUY0CDEO04+ZMoEhUowDDEO27NRMoEtUowDBEu27TBIpENQowDNHe2zOBIlGNAgxDtPNmb7BIVKMAwxDZOW/tBotENQowDJGd23ZesEhUowDDENU6b+kHi0Q1CjAM0X3nBm+wSFSjAMMQ2Xlu+gWLRDUKMAxRzdNWnbBIVKMAwxDhNG77BYtENQowDFHN2xZosEhUowDDENX8besJi0Q1CjAMEW7XJmiwSFSjAMMQ1XxugwaLRDUKMAxRzeumaLBIVKMAwxDV/G6LBotENQowDFHN88ZosEhUowDDENV8b9IJi0Q1CjAMEU7X9p6wSFSjAMMQ4TZu/AaLRDUKMAyRrd8Wn7BIVKMAwxDhtm73BotENQowDJGt00ZNoEhUowDDEPG0VRMoEtUowDBEfG3YBIpENQowDBFvWzaBIlGNAgxDxN+mTaBIVKMAwxDxuHETKBLVKMAwRHxu3QSKRDUKMAwRr5s3gSJRjQIMQ8TvNniwSFSjAMMQ2Xpv4wSKRDUKMAwR31v9wSJRjQIMQ3TjuuUfLBLVKMAwRDe+m+DBIlGNAgxDZOu7xRssEtUowDBEdr7b/MEiUY0CDEN047j1GywS1SjAMES2jhvhwSJRjQIMQ2TvtKknLBLVKMAwRLhNm6TBIlGNAgxDVPe1pSYkkkBUBvHguuEbLBLVKMAwRLZeG6XBIlGNAgxDVPe4nSYkkkBUBvHgu2kaLBLVKMAwRHWf26bBIlGNAgxDVPe7TRosEtUowDBEdW8bd8IiUY0CDEOE17R5JywS1SjAMER4XRunwSJRjQIMQ1T3vDEeLBLVKMAwRPZ+233CIlGNAgxDhN+1NR4sEtUowDBE9p5becIiUY0CDEOE17qREygS1SjAMEQ9beUEikQ1CjAMUW9bOoEiUY0CDEPU3zaakEgCURnEg/emTqBIVKMAwxD1uL0TKBLVKMAwRL1u7gmLRDUKMAwRbt8GT6BIVKMAwxD1vMUTKBLVKMAwRH1v9AeLRDUKMAzRjee2TqBIVKMAwxD1ufkbLBLVKMAwRLauW+XBIlGNAgxDZO+8hSYkkkBUBvHktH0mJJJAVAbx5LWVJiSSQFQG8eC8tR8sEtUowDBE992bfcIiUY0CDEOE37RxHiwS1SjAMEQ2XxtiAuI3hKHX926rCYkkEJVBPHhuiweLRDUKMAyRvdu2fJBIAlEZxJPjdp2wSFSjAMMQ4XRunQeLRDUKMAyRzdvWiJBIAlEZxJPfRnqwSFSjAMMQ2XxuxwaJJBCVQTy5bqUHi0Q1CjAMkc3v5nmwSFSjAMMQ2Txu9QSJJBCVQTx5b4kHiSQQlUE8eW6HCItENQowDNGd62Z6sEhUowDDENk8b50JiSQQlUE8uW2WB4tENQowDJG992Z+sEhUowDDEN23becHi0Q1CjAM0X3f9l+QSAJRGcST7+ZbkEgCURnEk/P2frBIVKMAwxDduG2VCItENQowDNGt00Z5sEhUowDDENm7brIEiSQQlUE8Om2RCItENQowDNGd92aKsEhUowDDEN06bvoHi0Q1CjAM0Y3zhnqwSFSjAMMQ2T1tqQeLRDUKMAyR3dfmf7BIVKMAwxDd+W2FCItENQowDNGd46Z6sEhUowDDENn9bawHi0Q1CjAMkd3jxp6wSFSjAMMQ4bZtrQeLRDUKMAyR3evmerBIVKMAwxDZ/W7wCYtENQowDBFu5yZ7sEhUowDDENl9b+sHi0Q1CjAM0X3zxn+wSFSjAMMQ3XltlwiLRDUKMAzRrdtWirBIVKMAwxDd+m3CCItENQowDNG912aIsEhUowDDEN15brUIi0Q1CjAM0a3r9oiwSFSjAMMQ3flukAiLRDUKMAzRnfMGjLBIVKMAwxDdem/uB4tENQowDNGN12aJsEhUowDDEN16bdMIi0Q1CjAM0b3ftn+wSFSjAMMQ3Tlt3giLRDUKMAzRveemfrBIVKMAwxDdt27gCItENQowDNG972aLsEhUowDDEN36btIIi0Q1CjAM0b3bZm6wSFSjAMMQ2Xhu1AiLRDUKMAzRveM2j7BIVKMAwxDdPG3fCItENQowDNG96+aPsEhUowDDEN18bfEIi0Q1CjAM0b3zBpiwSFSjAMMQ3fxtpwiLRDUKMAzRref2mLBIVKMAwxDdfG6OCYtENQowDNHN49Z/sEhUowDDEN25bZsJi0Q1CjAM0c3zxpmwSFSjAMMQ3Xxv8wmLRDUKMAwRbvMWjLBIVKMAwxDdO22aCYtENQowDNHN75aesEhUowDDEOF1b+MGi0Q1CjAMkY3bBpmwSFSjAMMQ3bxu/wiLRDUKMAzRzds3wETEREXNHyyOoNgtwiJRjQIMQ3TrvMkjLBLVKMAwRPfeG37CIlGNAgxDhN+25ScsEtUowDBE+H2bfsIiUY0CDEOE37jxJywS1SjAMET4ndt3wiJRjQIMQ4TXtsknLBLVKMAwRLi9G3nCIlGNAgxDhNe54SMgfkMYOX7f1pqwSFSjAMMQ3T1trgmLRDUKMAzR3df2mrBIVKMAwxDdvW2xCYtENQowDNHd3yabsEhUowDDEN09brMJi0Q1CjAM0d3nxpywSFSjAMMQ3b1uzQmLRDUKMAzR3e/mnLBIVKMAwxDdPW/mBYtENQowDFGt7wadsEhUowDDEN19b/UJi0Q1CjAMEW73hp6wSFSjAMMQ4TVv/QmLRDUKMAwRfuvmn7BIVKMAwxDh927aCYtENQowDBFO8xYZcDjU9FCTZMEEht8QRk0bYYHhN4RR19ZcYPgNYdS2ORoYfkMY9W3lBobfEEaN2+mB4TeEUeeGfmD4DWHUuqEiGH5DGPVu6wiI3xAGztu24SIYfkMYtm25CIbfEIZ9my6C4TeEYeO2i2D4DWHYufEiGH5DGLZuvQiG3xCGvZsvguE3hGHzpo5g+A1h2P0JLIIzEH+wOIJiWzKC4TeEcdemjGD4DWHcty0jGH5DGDduzAiG3xDGnds9guE3hHHrVo1g+A1h3LsdJhh+Qxg3b9YIht8Qxt3bNYLhN4SB04aNYPgNYeC1TSYYfkMYOG7/CUpDXNOPNANxmaACQlzIJDjNAAAAAAAAAGEgAAA3AAAAEwRBLBAAAAATAAAABBgBoNwIQCkGlGNAUQYUSJEUArFHAKhYgIllpBsjAEEQBEEQBFEdJMYIQBAEQRAEQRAECXqPJYAgCIIgCMJ7GxIgCIIgCIIgKIIEACMGBhCCYBAOr/A4Ozg8zDJsQATDAOzgADXLBfkdNiACYgB2cJAeZtiACI4B2MFhgphhAyKIBmAFCSpiogtsO2KQKCEIBu0QCwG1NAyGAwEACwAAACYawEgCURnEk++0j5hjwDBIjz0GMBLAPAvSGF9EQAewEM0UYX+wOIICAAAAAAAAAGEgAAA3AAAAEwRBLBAAAAATAAAABBgBoNwIQCkGlGNAUQYUSJEUArFHAKhYgIllpBsjAEEQBEEQBFEdJMYIQBAEQRAEQRAECXqPJYAgCIIgCMJ7GxIgCIIgCIIgKIIEACMGhhKCYBAOr/A4Ozg8zDJsQATDAOzgADXLBfkdNiACYgB2cJAeZtiACI4B2MFhgphhAyKIBmAFCSpiogtsO2KQKCEIBu0QCwG1NAyGAwEACwAAAOYYMAzSY6IBjiQQlUE8+U77iI/YYwAjAcyzII3xRQR0AAvRTBH2B4sjKAAAAAAAAHEgAABnAQAAUg4QImSCpBwgRMjkSDlAiJCh7rwXLAOxEBPBYIP0qNApgmQQ00kxKDU91CQx2CA9lkMUEUFUhWQM1+d0UDNMR4OYabE8LM/XA9QO09FzFzstfoXrdPRbblPUslSMzxCMREz+QyO8j+i4HoUjNAVASdPjWERk/0V1cMZwfU4HTdNnd5gNkr7r9LT7DGKmxfKwPK9DtQiRQUxi81DTCkwEgw3SUxFTO0xHz13stPg1fsPz8vQZTTeRY3KcZUIegyjAVTM9MxqI66kFyJxm08vyuYudFr/c4Xa5cBSkEUQMt+Fp97lkCKYRhDUqaFkqxi8Wx4n8yi50XHv2CxpgWRwBmAgGG6THAAyAmg4nqobJnGbTy/K5i50Wv+xl+Tz9dquPoQHSEBaDDdKjQZkIkUFMJ8WIzUNNEoMN0qNSvx8J0iATgw3SYy/D4hgVICmfUxZIWran52UySJwHSZuWsAyEJETIMyFOUweTMVyf00HEMjucBzHTYnlYntemzgQJaaQJaASCWwggYrBBegyFUBon0B9LgyugkGVwJSISm4mICkAgGGyQHn1CZWgYYgIGYAIYbJCeyoDkZXtZLp672Gnxyx1ul4uGDqg2GKgHoqfbZRAq7QbNy+O3mzxPgehvELk8DudBNhhZCEq7Qe00mcwug8RhN9lKgtpaArs2JnnZXpaL5y52Wvyyl+Xz9NttNgGuTPkIH9JIE9AIxEpIxORKRCQ2ExEVgEAw2CA9NhPcqkNewAyENEUOxmCD9NTExDxCmaB7mo4GlfHjMpyefrsNQ8mQCViJ6utOdcpNsJBGmoBGIDinkSagmSQGG6THVAiqQSa7IBqAIayoKBbHiSxGCLO6YQWjvByvl93jPAiF1KdAYTrojk6P0SA6ugxCp8/olllejtfL7nEeRLXBQOk5CB1mm0F0dBnUTpPJ7HJLHHaTT3MQ1QarD2iePrvD7LmLnRa/3OF2uWD8YCh/z+dve1kOMsvL8XrZPc6DUEh9CjQvw8PyMD3tPoPY7zso7CaD2mkymV0GmeXleL3sHqfLcyVaRpAMYkKp6aGmFZgIBhukp0CmefrsDrPnLnZa/LKX5fP0220FA+3T5jDYPl0SUTtMR89d7LT4xU6Py+55uUZ6wg/Spunhr7RsP81BaTe9LHeH2SAQCITD40DGcpksDo/XIGKZHc6DnGX6/S1fg1BGojMFMoGmY7T8XSaX5aAwmw0Pz+et8bstBsnL9rJcXJaH6W+5CwSalssgEAhkDNfn9NMcJC/by3Lx3MVOi0HmtxxEfo/r7bKbHqan325Q2E0GycvmsrzsHpfnhSCRy+xwfu5ip8Uve1k+T7/d5SHJ33V6ee5ip8Uve1k+T7/dxUAZw/U5HWRMs+llOYiZFsvD8nyRcNo0PfyVlu2gpJtelrvDbJCR6ARJy/ayXGxKwwQ0NbAZw/U5HSQMz9NjUJFdbpfddBAzLZaH5XlDGgRHspCjIiIJcZpSgANp2V6Wi0HkcvsNCsPh7PQ4TE+/3SBxeF4mg95uEFifpoe/8rL9aya7wS5zKSQBWIiqQZppMkhKtcEsiZCgaCqBRxyep8dzFzstfrnD7bJCNTcwgsM81EQw2CA9RSCJw/P0eO5ip8Uve1k+T7/dlbIHVBsM1APR0+0yCJV2g+bl8dtNnqdA9DeIXB6H8yAbjCwEpd0g9vveMsvL8XrZPc6DxGE32U4KacIWoiicdpiOnrvYafHLHW6XbSWQNMrwI0IaaQIagRAbZGKwQXqK45G/6/Ty3MVOi1/ucLtcFlE7TEfPXey0+GUvy+fpt9t4DAZYFkfQpXYER1gASRIbZGKwQXoUCBFBMoiJBZhnIVZgIhhskJ4yeMhldjg/d7HT4pc73C4XC8J830FSqg1WGpQxXJ/TQdKyvSwXg5hpsTwszwMAAAAAAAAAAA==",
					"bitcode_size" : 23768,
					"id" : "obj-19",
					"maxclass" : "newobj",
					"numinlets" : 8,
					"numoutlets" : 8,
					"outlettype" : [ "signal", "signal", "signal", "signal", "signal", "signal", "signal", "signal" ],
					"patching_rect" : [ 305.0, 272.0, 192.0, 22.0 ],
					"serial_number" : "C02Q6FVCG8WP32 bits",
					"sourcecode" : "declare name \"zitaRevFDN\";\ndeclare version \"0.0\";\ndeclare author \"JOS, Revised by RM\";\ndeclare description \"Reverb demo application based on `zita_rev_fdn`.\";\n\nimport(\"stdfaust.lib\");\n\nprocess = dm.zita_rev_fdn_demo;",
					"sourcecode_size" : 216,
					"style" : "",
					"text" : "faustgen~ zita",
					"varname" : "faustgen-842efa78",
					"version" : "1.12"
				}

			}
, 			{
				"box" : 				{
					"comment" : "",
					"id" : "obj-7",
					"maxclass" : "outlet",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 305.0, 383.375, 44.75, 44.75 ],
					"style" : ""
				}

			}
, 			{
				"box" : 				{
					"comment" : "",
					"id" : "obj-6",
					"maxclass" : "inlet",
					"numinlets" : 0,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 379.142853, 97.5, 51.0, 51.0 ],
					"style" : ""
				}

			}
 ],
		"lines" : [ 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 7 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 7 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 6 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 6 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 5 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 5 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 4 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 4 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 3 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 3 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 2 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 2 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 1 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 1 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 0 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-19", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 7 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 6 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 5 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 4 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 3 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 2 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 1 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-19", 0 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-7", 0 ],
					"disabled" : 0,
					"hidden" : 0,
					"source" : [ "obj-8", 0 ]
				}

			}
 ]
	}

}
